// GENERATED by home-protocol/gen from schema.yaml — do not edit.
#pragma once

#include "home_tlv.h"

#ifdef __cplusplus
extern "C" {
#endif

#define HP_PROTO_MAJOR 1
#define HP_PROTO_MINOR 0
#define HP_HEADER_VERSION 1
#define HP_HEADER_SIZE 6
#define HP_MAX_MESSAGE 2048
#define HP_TCP_PORT 7700
#define HP_DISCOVER_PORT 7701
#define HP_MDNS_SERVICE "_home._tcp"
#define HP_BLE_SERVICE_UUID "6e6f6d65-0001-4c9e-9a6e-686f6d650001"
#define HP_BLE_RX_UUID "6e6f6d65-0002-4c9e-9a6e-686f6d650001"
#define HP_BLE_TX_UUID "6e6f6d65-0003-4c9e-9a6e-686f6d650001"
#define HP_BLE_INFO_UUID "6e6f6d65-0004-4c9e-9a6e-686f6d650001"
#define HP_BLE_MANUFACTURER_ID 65535
#define HP_OTA_CHUNK 1024
#define HP_OTA_WINDOW 8

// Flags
enum {
    HP_FLAGS_RESP = 1,
    HP_FLAGS_ERR = 2,
    HP_FLAGS_NOACK = 4,
};

// ErrorCode
enum {
    HP_ERROR_CODE_OK = 0,
    HP_ERROR_CODE_UNSUPPORTED = 1,
    HP_ERROR_CODE_BAD_REQUEST = 2,
    HP_ERROR_CODE_NOT_FOUND = 3,
    HP_ERROR_CODE_FORBIDDEN = 4,
    HP_ERROR_CODE_BUSY = 5,
    HP_ERROR_CODE_INVALID_VALUE = 6,
    HP_ERROR_CODE_OTA_BAD_IMAGE = 7,
    HP_ERROR_CODE_OTA_HASH_MISMATCH = 8,
    HP_ERROR_CODE_OTA_WRONG_MODEL = 9,
    HP_ERROR_CODE_STORAGE = 10,
    HP_ERROR_CODE_SENSOR = 11,
    HP_ERROR_CODE_INTERNAL = 12,
    HP_ERROR_CODE_TIMEOUT = 13,
};

// Model
enum {
    HP_MODEL_UNKNOWN = 0,
    HP_MODEL_CO2_EGG = 1,
    HP_MODEL_RELAY = 2,
    HP_MODEL_BOARD_PROBE = 32512,
};

// PointKind
enum {
    HP_POINT_KIND_SENSOR = 0,
    HP_POINT_KIND_ACTUATOR = 1,
    HP_POINT_KIND_SETTING = 2,
    HP_POINT_KIND_ACTION = 3,
};

// PointType
enum {
    HP_POINT_TYPE_BOOL = 0,
    HP_POINT_TYPE_I32 = 1,
    HP_POINT_TYPE_F32 = 2,
    HP_POINT_TYPE_STR = 3,
    HP_POINT_TYPE_ENUM = 4,
};

// UiHint
enum {
    HP_UI_HINT_AUTO = 0,
    HP_UI_HINT_GAUGE = 1,
    HP_UI_HINT_SWITCH = 2,
    HP_UI_HINT_SLIDER = 3,
    HP_UI_HINT_BUTTON = 4,
    HP_UI_HINT_SELECT = 5,
    HP_UI_HINT_TEXT = 6,
    HP_UI_HINT_HIDDEN = 7,
};

// PointFlags
enum {
    HP_POINT_FLAGS_HISTORY = 1,
    HP_POINT_FLAGS_READONLY = 2,
    HP_POINT_FLAGS_ADVANCED = 4,
    HP_POINT_FLAGS_PERSIST = 8,
};

// ResetMode
enum {
    HP_RESET_MODE_SETTINGS = 1,
    HP_RESET_MODE_FIRMWARE = 2,
    HP_RESET_MODE_ALL = 3,
};

// BootPartition
enum {
    HP_BOOT_PARTITION_FACTORY = 0,
    HP_BOOT_PARTITION_OTA0 = 1,
    HP_BOOT_PARTITION_OTA1 = 2,
    HP_BOOT_PARTITION_UNKNOWN = 255,
};

// AdoptState
enum {
    HP_ADOPT_STATE_NEW = 0,
    HP_ADOPT_STATE_ADOPTED = 1,
    HP_ADOPT_STATE_BLOCKED = 2,
};

// IpMode
enum {
    HP_IP_MODE_DHCP = 0,
    HP_IP_MODE_STATIC = 1,
};

// BleMode
enum {
    HP_BLE_MODE_ALWAYS = 0,
    HP_BLE_MODE_BUTTON = 1,
    HP_BLE_MODE_OFF = 2,
};

// LogLevel
enum {
    HP_LOG_LEVEL_NONE = 0,
    HP_LOG_LEVEL_ERROR = 1,
    HP_LOG_LEVEL_WARN = 2,
    HP_LOG_LEVEL_INFO = 3,
    HP_LOG_LEVEL_DEBUG = 4,
    HP_LOG_LEVEL_VERBOSE = 5,
};

// WifiAuth
enum {
    HP_WIFI_AUTH_OPEN = 0,
    HP_WIFI_AUTH_WEP = 1,
    HP_WIFI_AUTH_WPA = 2,
    HP_WIFI_AUTH_WPA2 = 3,
    HP_WIFI_AUTH_WPA3 = 4,
    HP_WIFI_AUTH_OTHER = 5,
};

// LinkState
enum {
    HP_LINK_STATE_NO_CONFIG = 0,
    HP_LINK_STATE_WIFI_CONNECTING = 1,
    HP_LINK_STATE_IP_OK = 2,
    HP_LINK_STATE_SERVER_CONNECTING = 3,
    HP_LINK_STATE_ONLINE = 4,
};

// OtaState
enum {
    HP_OTA_STATE_IDLE = 0,
    HP_OTA_STATE_RECEIVING = 1,
    HP_OTA_STATE_VERIFYING = 2,
    HP_OTA_STATE_DONE = 3,
    HP_OTA_STATE_FAILED = 4,
};

// EventKind
enum {
    HP_EVENT_KIND_BOOT = 1,
    HP_EVENT_KIND_BUTTON = 2,
    HP_EVENT_KIND_THRESHOLD = 3,
    HP_EVENT_KIND_SENSOR_ERROR = 4,
    HP_EVENT_KIND_PREHEAT_DONE = 5,
};

// Message types
enum {
    HP_MSG_HELLO = 0x01,
    HP_MSG_PING = 0x03,
    HP_MSG_DESCRIBE = 0x10,
    HP_MSG_STATE = 0x11,
    HP_MSG_REPORT = 0x12,
    HP_MSG_SET = 0x13,
    HP_MSG_GET = 0x14,
    HP_MSG_INVOKE = 0x15,
    HP_MSG_EVENT = 0x16,
    HP_MSG_CFG_GET = 0x20,
    HP_MSG_CFG_SET = 0x21,
    HP_MSG_WIFI_SCAN = 0x22,
    HP_MSG_NET_STATUS = 0x23,
    HP_MSG_OTA_BEGIN = 0x30,
    HP_MSG_OTA_DATA = 0x31,
    HP_MSG_OTA_END = 0x32,
    HP_MSG_OTA_ABORT = 0x33,
    HP_MSG_OTA_STATUS = 0x34,
    HP_MSG_OTA_CONFIRM = 0x35,
    HP_MSG_REBOOT = 0x40,
    HP_MSG_FACTORY_RESET = 0x41,
    HP_MSG_IDENTIFY = 0x42,
    HP_MSG_LOG = 0x50,
    HP_MSG_PAIR_CODE = 0x60,
};

const char *hp_msg_name(uint8_t type);

typedef struct {
    bool has_b;
    bool b;
    bool has_i;
    int32_t i;
    bool has_f;
    float f;
    bool has_s;
    char s[65];
} hp_value_t;

void hp_value_write(htlv_writer_t *w, const hp_value_t *m);
hp_decode_result_t hp_value_read(hp_value_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_id;
    uint8_t id;
    bool has_key;
    char key[25];
    bool has_title;
    char title[49];
    bool has_kind;
    uint8_t kind;
    bool has_type;
    uint8_t type;
    bool has_unit;
    char unit[9];
    bool has_min;
    float min;
    bool has_max;
    float max;
    bool has_step;
    float step;
    size_t options_count;
    char options[8][17];
    bool has_ui;
    uint8_t ui;
    bool has_flags;
    uint8_t flags;
    bool has_thr_warn;
    float thr_warn;
    bool has_thr_alarm;
    float thr_alarm;
    bool has_has_arg;
    bool has_arg;
    bool has_arg_default;
    float arg_default;
} hp_point_def_t;

void hp_point_def_write(htlv_writer_t *w, const hp_point_def_t *m);
hp_decode_result_t hp_point_def_read(hp_point_def_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_point;
    uint8_t point;
    bool has_value;
    hp_value_t value;
    bool has_ts_ms;
    uint64_t ts_ms;
} hp_sample_t;

void hp_sample_write(htlv_writer_t *w, const hp_sample_t *m);
hp_decode_result_t hp_sample_read(hp_sample_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_ssid;
    char ssid[33];
    bool has_rssi;
    int32_t rssi;
    bool has_auth;
    uint8_t auth;
    bool has_channel;
    uint8_t channel;
} hp_wifi_net_t;

void hp_wifi_net_write(htlv_writer_t *w, const hp_wifi_net_t *m);
hp_decode_result_t hp_wifi_net_read(hp_wifi_net_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_ip_mode;
    uint8_t ip_mode;
    bool has_ip;
    uint32_t ip;
    bool has_mask;
    uint32_t mask;
    bool has_gw;
    uint32_t gw;
    bool has_dns1;
    uint32_t dns1;
    bool has_dns2;
    uint32_t dns2;
    bool has_hostname;
    char hostname[33];
} hp_net_config_t;

void hp_net_config_write(htlv_writer_t *w, const hp_net_config_t *m);
hp_decode_result_t hp_net_config_read(hp_net_config_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_name;
    char name[49];
    bool has_room;
    char room[49];
    bool has_wifi_ssid;
    char wifi_ssid[33];
    bool has_wifi_pass;
    char wifi_pass[65];
    bool has_net;
    hp_net_config_t net;
    bool has_server_host;
    char server_host[65];
    bool has_server_port;
    uint16_t server_port;
    bool has_ble_mode;
    uint8_t ble_mode;
    bool has_log_level;
    uint8_t log_level;
} hp_device_config_t;

void hp_device_config_write(htlv_writer_t *w, const hp_device_config_t *m);
hp_decode_result_t hp_device_config_read(hp_device_config_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_state;
    uint8_t state;
    bool has_current;
    hp_net_config_t current;
    bool has_rssi;
    int32_t rssi;
    bool has_ssid;
    char ssid[33];
    bool has_server;
    char server[65];
    bool has_mac;
    char mac[18];
} hp_net_status_t;

void hp_net_status_write(htlv_writer_t *w, const hp_net_status_t *m);
hp_decode_result_t hp_net_status_read(hp_net_status_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_code;
    uint8_t code;
    bool has_text;
    char text[97];
} hp_error_body_t;

void hp_error_body_write(htlv_writer_t *w, const hp_error_body_t *m);
hp_decode_result_t hp_error_body_read(hp_error_body_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_device_id;
    char device_id[13];
    bool has_model;
    uint16_t model;
    bool has_hw_rev;
    uint8_t hw_rev;
    bool has_fw_version;
    char fw_version[33];
    bool has_proto_major;
    uint8_t proto_major;
    bool has_proto_minor;
    uint8_t proto_minor;
    bool has_boot_partition;
    uint8_t boot_partition;
    bool has_reset_reason;
    uint8_t reset_reason;
    bool has_uptime_s;
    uint32_t uptime_s;
    bool has_name;
    char name[49];
    bool has_idf_version;
    char idf_version[33];
    bool has_pending_verify;
    bool pending_verify;
} hp_hello_req_t;

void hp_hello_req_write(htlv_writer_t *w, const hp_hello_req_t *m);
hp_decode_result_t hp_hello_req_read(hp_hello_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_time_ms;
    uint64_t time_ms;
    bool has_state;
    uint8_t state;
    bool has_log_level;
    uint8_t log_level;
} hp_hello_resp_t;

void hp_hello_resp_write(htlv_writer_t *w, const hp_hello_resp_t *m);
hp_decode_result_t hp_hello_resp_read(hp_hello_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_time_ms;
    uint64_t time_ms;
} hp_ping_req_t;

void hp_ping_req_write(htlv_writer_t *w, const hp_ping_req_t *m);
hp_decode_result_t hp_ping_req_read(hp_ping_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_time_ms;
    uint64_t time_ms;
} hp_ping_resp_t;

void hp_ping_resp_write(htlv_writer_t *w, const hp_ping_resp_t *m);
hp_decode_result_t hp_ping_resp_read(hp_ping_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_describe_req_t;

void hp_describe_req_write(htlv_writer_t *w, const hp_describe_req_t *m);
hp_decode_result_t hp_describe_req_read(hp_describe_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    size_t points_count;
    hp_point_def_t points[24];
} hp_describe_resp_t;

void hp_describe_resp_write(htlv_writer_t *w, const hp_describe_resp_t *m);
hp_decode_result_t hp_describe_resp_read(hp_describe_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    size_t samples_count;
    hp_sample_t samples[24];
} hp_state_req_t;

void hp_state_req_write(htlv_writer_t *w, const hp_state_req_t *m);
hp_decode_result_t hp_state_req_read(hp_state_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    size_t samples_count;
    hp_sample_t samples[24];
} hp_report_req_t;

void hp_report_req_write(htlv_writer_t *w, const hp_report_req_t *m);
hp_decode_result_t hp_report_req_read(hp_report_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_point;
    uint8_t point;
    bool has_value;
    hp_value_t value;
} hp_set_req_t;

void hp_set_req_write(htlv_writer_t *w, const hp_set_req_t *m);
hp_decode_result_t hp_set_req_read(hp_set_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_value;
    hp_value_t value;
} hp_set_resp_t;

void hp_set_resp_write(htlv_writer_t *w, const hp_set_resp_t *m);
hp_decode_result_t hp_set_resp_read(hp_set_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    size_t points_count;
    uint8_t points[24];
} hp_get_req_t;

void hp_get_req_write(htlv_writer_t *w, const hp_get_req_t *m);
hp_decode_result_t hp_get_req_read(hp_get_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    size_t samples_count;
    hp_sample_t samples[24];
} hp_get_resp_t;

void hp_get_resp_write(htlv_writer_t *w, const hp_get_resp_t *m);
hp_decode_result_t hp_get_resp_read(hp_get_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_point;
    uint8_t point;
    bool has_arg;
    float arg;
} hp_invoke_req_t;

void hp_invoke_req_write(htlv_writer_t *w, const hp_invoke_req_t *m);
hp_decode_result_t hp_invoke_req_read(hp_invoke_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_text;
    char text[97];
} hp_invoke_resp_t;

void hp_invoke_resp_write(htlv_writer_t *w, const hp_invoke_resp_t *m);
hp_decode_result_t hp_invoke_resp_read(hp_invoke_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_kind;
    uint8_t kind;
    bool has_point;
    uint8_t point;
    bool has_value;
    hp_value_t value;
    bool has_text;
    char text[97];
    bool has_ts_ms;
    uint64_t ts_ms;
} hp_event_req_t;

void hp_event_req_write(htlv_writer_t *w, const hp_event_req_t *m);
hp_decode_result_t hp_event_req_read(hp_event_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_cfg_get_req_t;

void hp_cfg_get_req_write(htlv_writer_t *w, const hp_cfg_get_req_t *m);
hp_decode_result_t hp_cfg_get_req_read(hp_cfg_get_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_config;
    hp_device_config_t config;
} hp_cfg_get_resp_t;

void hp_cfg_get_resp_write(htlv_writer_t *w, const hp_cfg_get_resp_t *m);
hp_decode_result_t hp_cfg_get_resp_read(hp_cfg_get_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_config;
    hp_device_config_t config;
} hp_cfg_set_req_t;

void hp_cfg_set_req_write(htlv_writer_t *w, const hp_cfg_set_req_t *m);
hp_decode_result_t hp_cfg_set_req_read(hp_cfg_set_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_cfg_set_resp_t;

void hp_cfg_set_resp_write(htlv_writer_t *w, const hp_cfg_set_resp_t *m);
hp_decode_result_t hp_cfg_set_resp_read(hp_cfg_set_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_wifi_scan_req_t;

void hp_wifi_scan_req_write(htlv_writer_t *w, const hp_wifi_scan_req_t *m);
hp_decode_result_t hp_wifi_scan_req_read(hp_wifi_scan_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    size_t networks_count;
    hp_wifi_net_t networks[20];
} hp_wifi_scan_resp_t;

void hp_wifi_scan_resp_write(htlv_writer_t *w, const hp_wifi_scan_resp_t *m);
hp_decode_result_t hp_wifi_scan_resp_read(hp_wifi_scan_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_net_status_req_t;

void hp_net_status_req_write(htlv_writer_t *w, const hp_net_status_req_t *m);
hp_decode_result_t hp_net_status_req_read(hp_net_status_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_status;
    hp_net_status_t status;
} hp_net_status_resp_t;

void hp_net_status_resp_write(htlv_writer_t *w, const hp_net_status_resp_t *m);
hp_decode_result_t hp_net_status_resp_read(hp_net_status_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_size;
    uint32_t size;
    bool has_sha256;
    const uint8_t *sha256;  // points into the decoded buffer (max 32)
    size_t sha256_len;
    bool has_version;
    char version[33];
    bool has_model;
    uint16_t model;
} hp_ota_begin_req_t;

void hp_ota_begin_req_write(htlv_writer_t *w, const hp_ota_begin_req_t *m);
hp_decode_result_t hp_ota_begin_req_read(hp_ota_begin_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_chunk;
    uint16_t chunk;
    bool has_resume_from;
    uint32_t resume_from;
} hp_ota_begin_resp_t;

void hp_ota_begin_resp_write(htlv_writer_t *w, const hp_ota_begin_resp_t *m);
hp_decode_result_t hp_ota_begin_resp_read(hp_ota_begin_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_offset;
    uint32_t offset;
    bool has_data;
    const uint8_t *data;  // points into the decoded buffer (max 1400)
    size_t data_len;
} hp_ota_data_req_t;

void hp_ota_data_req_write(htlv_writer_t *w, const hp_ota_data_req_t *m);
hp_decode_result_t hp_ota_data_req_read(hp_ota_data_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_next_offset;
    uint32_t next_offset;
} hp_ota_data_resp_t;

void hp_ota_data_resp_write(htlv_writer_t *w, const hp_ota_data_resp_t *m);
hp_decode_result_t hp_ota_data_resp_read(hp_ota_data_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_ota_end_req_t;

void hp_ota_end_req_write(htlv_writer_t *w, const hp_ota_end_req_t *m);
hp_decode_result_t hp_ota_end_req_read(hp_ota_end_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_ota_end_resp_t;

void hp_ota_end_resp_write(htlv_writer_t *w, const hp_ota_end_resp_t *m);
hp_decode_result_t hp_ota_end_resp_read(hp_ota_end_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_ota_abort_req_t;

void hp_ota_abort_req_write(htlv_writer_t *w, const hp_ota_abort_req_t *m);
hp_decode_result_t hp_ota_abort_req_read(hp_ota_abort_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_ota_abort_resp_t;

void hp_ota_abort_resp_write(htlv_writer_t *w, const hp_ota_abort_resp_t *m);
hp_decode_result_t hp_ota_abort_resp_read(hp_ota_abort_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_ota_status_req_t;

void hp_ota_status_req_write(htlv_writer_t *w, const hp_ota_status_req_t *m);
hp_decode_result_t hp_ota_status_req_read(hp_ota_status_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_state;
    uint8_t state;
    bool has_received;
    uint32_t received;
    bool has_error;
    uint8_t error;
} hp_ota_status_resp_t;

void hp_ota_status_resp_write(htlv_writer_t *w, const hp_ota_status_resp_t *m);
hp_decode_result_t hp_ota_status_resp_read(hp_ota_status_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_ota_confirm_req_t;

void hp_ota_confirm_req_write(htlv_writer_t *w, const hp_ota_confirm_req_t *m);
hp_decode_result_t hp_ota_confirm_req_read(hp_ota_confirm_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_ota_confirm_resp_t;

void hp_ota_confirm_resp_write(htlv_writer_t *w, const hp_ota_confirm_resp_t *m);
hp_decode_result_t hp_ota_confirm_resp_read(hp_ota_confirm_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_reboot_req_t;

void hp_reboot_req_write(htlv_writer_t *w, const hp_reboot_req_t *m);
hp_decode_result_t hp_reboot_req_read(hp_reboot_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_reboot_resp_t;

void hp_reboot_resp_write(htlv_writer_t *w, const hp_reboot_resp_t *m);
hp_decode_result_t hp_reboot_resp_read(hp_reboot_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_mode;
    uint8_t mode;
} hp_factory_reset_req_t;

void hp_factory_reset_req_write(htlv_writer_t *w, const hp_factory_reset_req_t *m);
hp_decode_result_t hp_factory_reset_req_read(hp_factory_reset_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_factory_reset_resp_t;

void hp_factory_reset_resp_write(htlv_writer_t *w, const hp_factory_reset_resp_t *m);
hp_decode_result_t hp_factory_reset_resp_read(hp_factory_reset_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_seconds;
    uint8_t seconds;
} hp_identify_req_t;

void hp_identify_req_write(htlv_writer_t *w, const hp_identify_req_t *m);
hp_decode_result_t hp_identify_req_read(hp_identify_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_identify_resp_t;

void hp_identify_resp_write(htlv_writer_t *w, const hp_identify_resp_t *m);
hp_decode_result_t hp_identify_resp_read(hp_identify_resp_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_level;
    uint8_t level;
    bool has_tag;
    char tag[17];
    bool has_text;
    char text[201];
    bool has_ts_ms;
    uint64_t ts_ms;
} hp_log_req_t;

void hp_log_req_write(htlv_writer_t *w, const hp_log_req_t *m);
hp_decode_result_t hp_log_req_read(hp_log_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    bool has_code;
    uint16_t code;
} hp_pair_code_req_t;

void hp_pair_code_req_write(htlv_writer_t *w, const hp_pair_code_req_t *m);
hp_decode_result_t hp_pair_code_req_read(hp_pair_code_req_t *m, const uint8_t *p, size_t n);

typedef struct {
    uint8_t _unused;
} hp_pair_code_resp_t;

void hp_pair_code_resp_write(htlv_writer_t *w, const hp_pair_code_resp_t *m);
hp_decode_result_t hp_pair_code_resp_read(hp_pair_code_resp_t *m, const uint8_t *p, size_t n);

#ifdef __cplusplus
}
#endif
