// GENERATED by home-protocol/gen from schema.yaml — do not edit.
#include <stdlib.h>
#include "home_proto.h"

#define RT(T, NAME) do { T *m = calloc(1, sizeof(T)); if (!m) return -1; \
    int rc = (int)NAME##_read(m, body, n); if (rc == 0) NAME##_write(w, m); free(m); return rc; } while (0)

// kind: 0 request, 1 response, 2 error body. Returns hp_decode_result_t or -2 for an unknown type.
int hp_test_roundtrip(uint8_t type, int kind, const uint8_t *body, size_t n, htlv_writer_t *w)
{
    if (kind == 2) RT(hp_error_body_t, hp_error_body);
    switch (type) {
    case HP_MSG_HELLO:
        if (kind == 0) RT(hp_hello_req_t, hp_hello_req);
        RT(hp_hello_resp_t, hp_hello_resp);
    case HP_MSG_PING:
        if (kind == 0) RT(hp_ping_req_t, hp_ping_req);
        RT(hp_ping_resp_t, hp_ping_resp);
    case HP_MSG_DESCRIBE:
        if (kind == 0) RT(hp_describe_req_t, hp_describe_req);
        RT(hp_describe_resp_t, hp_describe_resp);
    case HP_MSG_STATE:
        if (kind == 0) RT(hp_state_req_t, hp_state_req);
        return -2;
    case HP_MSG_REPORT:
        if (kind == 0) RT(hp_report_req_t, hp_report_req);
        return -2;
    case HP_MSG_SET:
        if (kind == 0) RT(hp_set_req_t, hp_set_req);
        RT(hp_set_resp_t, hp_set_resp);
    case HP_MSG_GET:
        if (kind == 0) RT(hp_get_req_t, hp_get_req);
        RT(hp_get_resp_t, hp_get_resp);
    case HP_MSG_INVOKE:
        if (kind == 0) RT(hp_invoke_req_t, hp_invoke_req);
        RT(hp_invoke_resp_t, hp_invoke_resp);
    case HP_MSG_EVENT:
        if (kind == 0) RT(hp_event_req_t, hp_event_req);
        return -2;
    case HP_MSG_CFG_GET:
        if (kind == 0) RT(hp_cfg_get_req_t, hp_cfg_get_req);
        RT(hp_cfg_get_resp_t, hp_cfg_get_resp);
    case HP_MSG_CFG_SET:
        if (kind == 0) RT(hp_cfg_set_req_t, hp_cfg_set_req);
        RT(hp_cfg_set_resp_t, hp_cfg_set_resp);
    case HP_MSG_WIFI_SCAN:
        if (kind == 0) RT(hp_wifi_scan_req_t, hp_wifi_scan_req);
        RT(hp_wifi_scan_resp_t, hp_wifi_scan_resp);
    case HP_MSG_NET_STATUS:
        if (kind == 0) RT(hp_net_status_req_t, hp_net_status_req);
        RT(hp_net_status_resp_t, hp_net_status_resp);
    case HP_MSG_OTA_BEGIN:
        if (kind == 0) RT(hp_ota_begin_req_t, hp_ota_begin_req);
        RT(hp_ota_begin_resp_t, hp_ota_begin_resp);
    case HP_MSG_OTA_DATA:
        if (kind == 0) RT(hp_ota_data_req_t, hp_ota_data_req);
        RT(hp_ota_data_resp_t, hp_ota_data_resp);
    case HP_MSG_OTA_END:
        if (kind == 0) RT(hp_ota_end_req_t, hp_ota_end_req);
        RT(hp_ota_end_resp_t, hp_ota_end_resp);
    case HP_MSG_OTA_ABORT:
        if (kind == 0) RT(hp_ota_abort_req_t, hp_ota_abort_req);
        RT(hp_ota_abort_resp_t, hp_ota_abort_resp);
    case HP_MSG_OTA_STATUS:
        if (kind == 0) RT(hp_ota_status_req_t, hp_ota_status_req);
        RT(hp_ota_status_resp_t, hp_ota_status_resp);
    case HP_MSG_OTA_CONFIRM:
        if (kind == 0) RT(hp_ota_confirm_req_t, hp_ota_confirm_req);
        RT(hp_ota_confirm_resp_t, hp_ota_confirm_resp);
    case HP_MSG_REBOOT:
        if (kind == 0) RT(hp_reboot_req_t, hp_reboot_req);
        RT(hp_reboot_resp_t, hp_reboot_resp);
    case HP_MSG_FACTORY_RESET:
        if (kind == 0) RT(hp_factory_reset_req_t, hp_factory_reset_req);
        RT(hp_factory_reset_resp_t, hp_factory_reset_resp);
    case HP_MSG_IDENTIFY:
        if (kind == 0) RT(hp_identify_req_t, hp_identify_req);
        RT(hp_identify_resp_t, hp_identify_resp);
    case HP_MSG_LOG:
        if (kind == 0) RT(hp_log_req_t, hp_log_req);
        return -2;
    case HP_MSG_PAIR_CODE:
        if (kind == 0) RT(hp_pair_code_req_t, hp_pair_code_req);
        RT(hp_pair_code_resp_t, hp_pair_code_resp);
    default:
        return -2;
    }
}
