// GENERATED by home-protocol/gen from schema.yaml — do not edit.
#include "home_proto.h"

#include <string.h>

const char *hp_msg_name(uint8_t type)
{
    switch (type) {
    case HP_MSG_HELLO: return "HELLO";
    case HP_MSG_PING: return "PING";
    case HP_MSG_DESCRIBE: return "DESCRIBE";
    case HP_MSG_STATE: return "STATE";
    case HP_MSG_REPORT: return "REPORT";
    case HP_MSG_SET: return "SET";
    case HP_MSG_GET: return "GET";
    case HP_MSG_INVOKE: return "INVOKE";
    case HP_MSG_EVENT: return "EVENT";
    case HP_MSG_CFG_GET: return "CFG_GET";
    case HP_MSG_CFG_SET: return "CFG_SET";
    case HP_MSG_WIFI_SCAN: return "WIFI_SCAN";
    case HP_MSG_NET_STATUS: return "NET_STATUS";
    case HP_MSG_OTA_BEGIN: return "OTA_BEGIN";
    case HP_MSG_OTA_DATA: return "OTA_DATA";
    case HP_MSG_OTA_END: return "OTA_END";
    case HP_MSG_OTA_ABORT: return "OTA_ABORT";
    case HP_MSG_OTA_STATUS: return "OTA_STATUS";
    case HP_MSG_OTA_CONFIRM: return "OTA_CONFIRM";
    case HP_MSG_REBOOT: return "REBOOT";
    case HP_MSG_FACTORY_RESET: return "FACTORY_RESET";
    case HP_MSG_IDENTIFY: return "IDENTIFY";
    case HP_MSG_LOG: return "LOG";
    case HP_MSG_PAIR_CODE: return "PAIR_CODE";
    default: return "?";
    }
}

void hp_value_write(htlv_writer_t *w, const hp_value_t *m)
{
    if (m->has_b) {
        htlv_w_bool(w, 0x01, m->b);
    }
    if (m->has_i) {
        htlv_w_i32(w, 0x02, m->i);
    }
    if (m->has_f) {
        htlv_w_f32(w, 0x03, m->f);
    }
    if (m->has_s) {
        htlv_w_str(w, 0x04, m->s);
    }
}

hp_decode_result_t hp_value_read(hp_value_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_bool(v, vn, &m->b)) return HP_DECODE_MALFORMED;
            m->has_b = true;
            break;
        case 2:
            if (!htlv_get_i32(v, vn, &m->i)) return HP_DECODE_MALFORMED;
            m->has_i = true;
            break;
        case 3:
            if (!htlv_get_f32(v, vn, &m->f)) return HP_DECODE_MALFORMED;
            m->has_f = true;
            break;
        case 4:
            if (!htlv_get_str(v, vn, m->s, sizeof m->s)) return HP_DECODE_TOO_LONG;
            m->has_s = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_point_def_write(htlv_writer_t *w, const hp_point_def_t *m)
{
    if (m->has_id) {
        htlv_w_u8(w, 0x81, m->id);
    }
    if (m->has_key) {
        htlv_w_str(w, 0x02, m->key);
    }
    if (m->has_title) {
        htlv_w_str(w, 0x03, m->title);
    }
    if (m->has_kind) {
        htlv_w_u8(w, 0x04, m->kind);
    }
    if (m->has_type) {
        htlv_w_u8(w, 0x05, m->type);
    }
    if (m->has_unit) {
        htlv_w_str(w, 0x06, m->unit);
    }
    if (m->has_min) {
        htlv_w_f32(w, 0x07, m->min);
    }
    if (m->has_max) {
        htlv_w_f32(w, 0x08, m->max);
    }
    if (m->has_step) {
        htlv_w_f32(w, 0x09, m->step);
    }
    for (size_t i = 0; i < m->options_count && i < 8; i++) {
        htlv_w_str(w, 0x0A, m->options[i]);
    }
    if (m->has_ui) {
        htlv_w_u8(w, 0x0B, m->ui);
    }
    if (m->has_flags) {
        htlv_w_u8(w, 0x0C, m->flags);
    }
    if (m->has_thr_warn) {
        htlv_w_f32(w, 0x0D, m->thr_warn);
    }
    if (m->has_thr_alarm) {
        htlv_w_f32(w, 0x0E, m->thr_alarm);
    }
    if (m->has_has_arg) {
        htlv_w_bool(w, 0x0F, m->has_arg);
    }
    if (m->has_arg_default) {
        htlv_w_f32(w, 0x10, m->arg_default);
    }
}

hp_decode_result_t hp_point_def_read(hp_point_def_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u8(v, vn, &m->id)) return HP_DECODE_MALFORMED;
            m->has_id = true;
            break;
        case 2:
            if (!htlv_get_str(v, vn, m->key, sizeof m->key)) return HP_DECODE_TOO_LONG;
            m->has_key = true;
            break;
        case 3:
            if (!htlv_get_str(v, vn, m->title, sizeof m->title)) return HP_DECODE_TOO_LONG;
            m->has_title = true;
            break;
        case 4:
            if (!htlv_get_u8(v, vn, &m->kind)) return HP_DECODE_MALFORMED;
            m->has_kind = true;
            break;
        case 5:
            if (!htlv_get_u8(v, vn, &m->type)) return HP_DECODE_MALFORMED;
            m->has_type = true;
            break;
        case 6:
            if (!htlv_get_str(v, vn, m->unit, sizeof m->unit)) return HP_DECODE_TOO_LONG;
            m->has_unit = true;
            break;
        case 7:
            if (!htlv_get_f32(v, vn, &m->min)) return HP_DECODE_MALFORMED;
            m->has_min = true;
            break;
        case 8:
            if (!htlv_get_f32(v, vn, &m->max)) return HP_DECODE_MALFORMED;
            m->has_max = true;
            break;
        case 9:
            if (!htlv_get_f32(v, vn, &m->step)) return HP_DECODE_MALFORMED;
            m->has_step = true;
            break;
        case 10:
            if (m->options_count >= 8) return HP_DECODE_TOO_LONG;
            if (!htlv_get_str(v, vn, m->options[m->options_count], sizeof m->options[0])) return HP_DECODE_TOO_LONG;
            m->options_count++;
            break;
        case 11:
            if (!htlv_get_u8(v, vn, &m->ui)) return HP_DECODE_MALFORMED;
            m->has_ui = true;
            break;
        case 12:
            if (!htlv_get_u8(v, vn, &m->flags)) return HP_DECODE_MALFORMED;
            m->has_flags = true;
            break;
        case 13:
            if (!htlv_get_f32(v, vn, &m->thr_warn)) return HP_DECODE_MALFORMED;
            m->has_thr_warn = true;
            break;
        case 14:
            if (!htlv_get_f32(v, vn, &m->thr_alarm)) return HP_DECODE_MALFORMED;
            m->has_thr_alarm = true;
            break;
        case 15:
            if (!htlv_get_bool(v, vn, &m->has_arg)) return HP_DECODE_MALFORMED;
            m->has_has_arg = true;
            break;
        case 16:
            if (!htlv_get_f32(v, vn, &m->arg_default)) return HP_DECODE_MALFORMED;
            m->has_arg_default = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_sample_write(htlv_writer_t *w, const hp_sample_t *m)
{
    if (m->has_point) {
        htlv_w_u8(w, 0x81, m->point);
    }
    if (m->has_value) {
        size_t mark = htlv_w_begin(w, 0x02);
        hp_value_write(w, &m->value);
        htlv_w_end(w, mark);
    }
    if (m->has_ts_ms) {
        htlv_w_u64(w, 0x03, m->ts_ms);
    }
}

hp_decode_result_t hp_sample_read(hp_sample_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u8(v, vn, &m->point)) return HP_DECODE_MALFORMED;
            m->has_point = true;
            break;
        case 2:
            {
                hp_decode_result_t sub = hp_value_read(&m->value, v, vn);
                if (sub != HP_DECODE_OK) return sub;
            }
            m->has_value = true;
            break;
        case 3:
            if (!htlv_get_u64(v, vn, &m->ts_ms)) return HP_DECODE_MALFORMED;
            m->has_ts_ms = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_wifi_net_write(htlv_writer_t *w, const hp_wifi_net_t *m)
{
    if (m->has_ssid) {
        htlv_w_str(w, 0x01, m->ssid);
    }
    if (m->has_rssi) {
        htlv_w_i32(w, 0x02, m->rssi);
    }
    if (m->has_auth) {
        htlv_w_u8(w, 0x03, m->auth);
    }
    if (m->has_channel) {
        htlv_w_u8(w, 0x04, m->channel);
    }
}

hp_decode_result_t hp_wifi_net_read(hp_wifi_net_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_str(v, vn, m->ssid, sizeof m->ssid)) return HP_DECODE_TOO_LONG;
            m->has_ssid = true;
            break;
        case 2:
            if (!htlv_get_i32(v, vn, &m->rssi)) return HP_DECODE_MALFORMED;
            m->has_rssi = true;
            break;
        case 3:
            if (!htlv_get_u8(v, vn, &m->auth)) return HP_DECODE_MALFORMED;
            m->has_auth = true;
            break;
        case 4:
            if (!htlv_get_u8(v, vn, &m->channel)) return HP_DECODE_MALFORMED;
            m->has_channel = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_net_config_write(htlv_writer_t *w, const hp_net_config_t *m)
{
    if (m->has_ip_mode) {
        htlv_w_u8(w, 0x01, m->ip_mode);
    }
    if (m->has_ip) {
        htlv_w_u32(w, 0x02, m->ip);
    }
    if (m->has_mask) {
        htlv_w_u32(w, 0x03, m->mask);
    }
    if (m->has_gw) {
        htlv_w_u32(w, 0x04, m->gw);
    }
    if (m->has_dns1) {
        htlv_w_u32(w, 0x05, m->dns1);
    }
    if (m->has_dns2) {
        htlv_w_u32(w, 0x06, m->dns2);
    }
    if (m->has_hostname) {
        htlv_w_str(w, 0x07, m->hostname);
    }
}

hp_decode_result_t hp_net_config_read(hp_net_config_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u8(v, vn, &m->ip_mode)) return HP_DECODE_MALFORMED;
            m->has_ip_mode = true;
            break;
        case 2:
            if (!htlv_get_u32(v, vn, &m->ip)) return HP_DECODE_MALFORMED;
            m->has_ip = true;
            break;
        case 3:
            if (!htlv_get_u32(v, vn, &m->mask)) return HP_DECODE_MALFORMED;
            m->has_mask = true;
            break;
        case 4:
            if (!htlv_get_u32(v, vn, &m->gw)) return HP_DECODE_MALFORMED;
            m->has_gw = true;
            break;
        case 5:
            if (!htlv_get_u32(v, vn, &m->dns1)) return HP_DECODE_MALFORMED;
            m->has_dns1 = true;
            break;
        case 6:
            if (!htlv_get_u32(v, vn, &m->dns2)) return HP_DECODE_MALFORMED;
            m->has_dns2 = true;
            break;
        case 7:
            if (!htlv_get_str(v, vn, m->hostname, sizeof m->hostname)) return HP_DECODE_TOO_LONG;
            m->has_hostname = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_device_config_write(htlv_writer_t *w, const hp_device_config_t *m)
{
    if (m->has_name) {
        htlv_w_str(w, 0x01, m->name);
    }
    if (m->has_room) {
        htlv_w_str(w, 0x02, m->room);
    }
    if (m->has_wifi_ssid) {
        htlv_w_str(w, 0x03, m->wifi_ssid);
    }
    if (m->has_wifi_pass) {
        htlv_w_str(w, 0x04, m->wifi_pass);
    }
    if (m->has_net) {
        size_t mark = htlv_w_begin(w, 0x05);
        hp_net_config_write(w, &m->net);
        htlv_w_end(w, mark);
    }
    if (m->has_server_host) {
        htlv_w_str(w, 0x06, m->server_host);
    }
    if (m->has_server_port) {
        htlv_w_u16(w, 0x07, m->server_port);
    }
    if (m->has_ble_mode) {
        htlv_w_u8(w, 0x08, m->ble_mode);
    }
    if (m->has_log_level) {
        htlv_w_u8(w, 0x09, m->log_level);
    }
}

hp_decode_result_t hp_device_config_read(hp_device_config_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_str(v, vn, m->name, sizeof m->name)) return HP_DECODE_TOO_LONG;
            m->has_name = true;
            break;
        case 2:
            if (!htlv_get_str(v, vn, m->room, sizeof m->room)) return HP_DECODE_TOO_LONG;
            m->has_room = true;
            break;
        case 3:
            if (!htlv_get_str(v, vn, m->wifi_ssid, sizeof m->wifi_ssid)) return HP_DECODE_TOO_LONG;
            m->has_wifi_ssid = true;
            break;
        case 4:
            if (!htlv_get_str(v, vn, m->wifi_pass, sizeof m->wifi_pass)) return HP_DECODE_TOO_LONG;
            m->has_wifi_pass = true;
            break;
        case 5:
            {
                hp_decode_result_t sub = hp_net_config_read(&m->net, v, vn);
                if (sub != HP_DECODE_OK) return sub;
            }
            m->has_net = true;
            break;
        case 6:
            if (!htlv_get_str(v, vn, m->server_host, sizeof m->server_host)) return HP_DECODE_TOO_LONG;
            m->has_server_host = true;
            break;
        case 7:
            if (!htlv_get_u16(v, vn, &m->server_port)) return HP_DECODE_MALFORMED;
            m->has_server_port = true;
            break;
        case 8:
            if (!htlv_get_u8(v, vn, &m->ble_mode)) return HP_DECODE_MALFORMED;
            m->has_ble_mode = true;
            break;
        case 9:
            if (!htlv_get_u8(v, vn, &m->log_level)) return HP_DECODE_MALFORMED;
            m->has_log_level = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_net_status_write(htlv_writer_t *w, const hp_net_status_t *m)
{
    if (m->has_state) {
        htlv_w_u8(w, 0x01, m->state);
    }
    if (m->has_current) {
        size_t mark = htlv_w_begin(w, 0x02);
        hp_net_config_write(w, &m->current);
        htlv_w_end(w, mark);
    }
    if (m->has_rssi) {
        htlv_w_i32(w, 0x03, m->rssi);
    }
    if (m->has_ssid) {
        htlv_w_str(w, 0x04, m->ssid);
    }
    if (m->has_server) {
        htlv_w_str(w, 0x05, m->server);
    }
    if (m->has_mac) {
        htlv_w_str(w, 0x06, m->mac);
    }
}

hp_decode_result_t hp_net_status_read(hp_net_status_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u8(v, vn, &m->state)) return HP_DECODE_MALFORMED;
            m->has_state = true;
            break;
        case 2:
            {
                hp_decode_result_t sub = hp_net_config_read(&m->current, v, vn);
                if (sub != HP_DECODE_OK) return sub;
            }
            m->has_current = true;
            break;
        case 3:
            if (!htlv_get_i32(v, vn, &m->rssi)) return HP_DECODE_MALFORMED;
            m->has_rssi = true;
            break;
        case 4:
            if (!htlv_get_str(v, vn, m->ssid, sizeof m->ssid)) return HP_DECODE_TOO_LONG;
            m->has_ssid = true;
            break;
        case 5:
            if (!htlv_get_str(v, vn, m->server, sizeof m->server)) return HP_DECODE_TOO_LONG;
            m->has_server = true;
            break;
        case 6:
            if (!htlv_get_str(v, vn, m->mac, sizeof m->mac)) return HP_DECODE_TOO_LONG;
            m->has_mac = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_error_body_write(htlv_writer_t *w, const hp_error_body_t *m)
{
    if (m->has_code) {
        htlv_w_u8(w, 0x01, m->code);
    }
    if (m->has_text) {
        htlv_w_str(w, 0x02, m->text);
    }
}

hp_decode_result_t hp_error_body_read(hp_error_body_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u8(v, vn, &m->code)) return HP_DECODE_MALFORMED;
            m->has_code = true;
            break;
        case 2:
            if (!htlv_get_str(v, vn, m->text, sizeof m->text)) return HP_DECODE_TOO_LONG;
            m->has_text = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_hello_req_write(htlv_writer_t *w, const hp_hello_req_t *m)
{
    if (m->has_device_id) {
        htlv_w_str(w, 0x81, m->device_id);
    }
    if (m->has_model) {
        htlv_w_u16(w, 0x02, m->model);
    }
    if (m->has_hw_rev) {
        htlv_w_u8(w, 0x03, m->hw_rev);
    }
    if (m->has_fw_version) {
        htlv_w_str(w, 0x04, m->fw_version);
    }
    if (m->has_proto_major) {
        htlv_w_u8(w, 0x05, m->proto_major);
    }
    if (m->has_proto_minor) {
        htlv_w_u8(w, 0x06, m->proto_minor);
    }
    if (m->has_boot_partition) {
        htlv_w_u8(w, 0x07, m->boot_partition);
    }
    if (m->has_reset_reason) {
        htlv_w_u8(w, 0x08, m->reset_reason);
    }
    if (m->has_uptime_s) {
        htlv_w_u32(w, 0x09, m->uptime_s);
    }
    if (m->has_name) {
        htlv_w_str(w, 0x0A, m->name);
    }
    if (m->has_idf_version) {
        htlv_w_str(w, 0x0B, m->idf_version);
    }
    if (m->has_pending_verify) {
        htlv_w_bool(w, 0x0C, m->pending_verify);
    }
}

hp_decode_result_t hp_hello_req_read(hp_hello_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_str(v, vn, m->device_id, sizeof m->device_id)) return HP_DECODE_TOO_LONG;
            m->has_device_id = true;
            break;
        case 2:
            if (!htlv_get_u16(v, vn, &m->model)) return HP_DECODE_MALFORMED;
            m->has_model = true;
            break;
        case 3:
            if (!htlv_get_u8(v, vn, &m->hw_rev)) return HP_DECODE_MALFORMED;
            m->has_hw_rev = true;
            break;
        case 4:
            if (!htlv_get_str(v, vn, m->fw_version, sizeof m->fw_version)) return HP_DECODE_TOO_LONG;
            m->has_fw_version = true;
            break;
        case 5:
            if (!htlv_get_u8(v, vn, &m->proto_major)) return HP_DECODE_MALFORMED;
            m->has_proto_major = true;
            break;
        case 6:
            if (!htlv_get_u8(v, vn, &m->proto_minor)) return HP_DECODE_MALFORMED;
            m->has_proto_minor = true;
            break;
        case 7:
            if (!htlv_get_u8(v, vn, &m->boot_partition)) return HP_DECODE_MALFORMED;
            m->has_boot_partition = true;
            break;
        case 8:
            if (!htlv_get_u8(v, vn, &m->reset_reason)) return HP_DECODE_MALFORMED;
            m->has_reset_reason = true;
            break;
        case 9:
            if (!htlv_get_u32(v, vn, &m->uptime_s)) return HP_DECODE_MALFORMED;
            m->has_uptime_s = true;
            break;
        case 10:
            if (!htlv_get_str(v, vn, m->name, sizeof m->name)) return HP_DECODE_TOO_LONG;
            m->has_name = true;
            break;
        case 11:
            if (!htlv_get_str(v, vn, m->idf_version, sizeof m->idf_version)) return HP_DECODE_TOO_LONG;
            m->has_idf_version = true;
            break;
        case 12:
            if (!htlv_get_bool(v, vn, &m->pending_verify)) return HP_DECODE_MALFORMED;
            m->has_pending_verify = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_hello_resp_write(htlv_writer_t *w, const hp_hello_resp_t *m)
{
    if (m->has_time_ms) {
        htlv_w_u64(w, 0x01, m->time_ms);
    }
    if (m->has_state) {
        htlv_w_u8(w, 0x02, m->state);
    }
    if (m->has_log_level) {
        htlv_w_u8(w, 0x03, m->log_level);
    }
}

hp_decode_result_t hp_hello_resp_read(hp_hello_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u64(v, vn, &m->time_ms)) return HP_DECODE_MALFORMED;
            m->has_time_ms = true;
            break;
        case 2:
            if (!htlv_get_u8(v, vn, &m->state)) return HP_DECODE_MALFORMED;
            m->has_state = true;
            break;
        case 3:
            if (!htlv_get_u8(v, vn, &m->log_level)) return HP_DECODE_MALFORMED;
            m->has_log_level = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_ping_req_write(htlv_writer_t *w, const hp_ping_req_t *m)
{
    if (m->has_time_ms) {
        htlv_w_u64(w, 0x01, m->time_ms);
    }
}

hp_decode_result_t hp_ping_req_read(hp_ping_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u64(v, vn, &m->time_ms)) return HP_DECODE_MALFORMED;
            m->has_time_ms = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_ping_resp_write(htlv_writer_t *w, const hp_ping_resp_t *m)
{
    if (m->has_time_ms) {
        htlv_w_u64(w, 0x01, m->time_ms);
    }
}

hp_decode_result_t hp_ping_resp_read(hp_ping_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u64(v, vn, &m->time_ms)) return HP_DECODE_MALFORMED;
            m->has_time_ms = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_describe_req_write(htlv_writer_t *w, const hp_describe_req_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_describe_req_read(hp_describe_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_describe_resp_write(htlv_writer_t *w, const hp_describe_resp_t *m)
{
    for (size_t i = 0; i < m->points_count && i < 24; i++) {
        size_t mark = htlv_w_begin(w, 0x01);
        hp_point_def_write(w, &m->points[i]);
        htlv_w_end(w, mark);
    }
}

hp_decode_result_t hp_describe_resp_read(hp_describe_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (m->points_count >= 24) return HP_DECODE_TOO_LONG;
            {
                hp_decode_result_t sub = hp_point_def_read(&m->points[m->points_count], v, vn);
                if (sub != HP_DECODE_OK) return sub;
            }
            m->points_count++;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_state_req_write(htlv_writer_t *w, const hp_state_req_t *m)
{
    for (size_t i = 0; i < m->samples_count && i < 24; i++) {
        size_t mark = htlv_w_begin(w, 0x01);
        hp_sample_write(w, &m->samples[i]);
        htlv_w_end(w, mark);
    }
}

hp_decode_result_t hp_state_req_read(hp_state_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (m->samples_count >= 24) return HP_DECODE_TOO_LONG;
            {
                hp_decode_result_t sub = hp_sample_read(&m->samples[m->samples_count], v, vn);
                if (sub != HP_DECODE_OK) return sub;
            }
            m->samples_count++;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_report_req_write(htlv_writer_t *w, const hp_report_req_t *m)
{
    for (size_t i = 0; i < m->samples_count && i < 24; i++) {
        size_t mark = htlv_w_begin(w, 0x01);
        hp_sample_write(w, &m->samples[i]);
        htlv_w_end(w, mark);
    }
}

hp_decode_result_t hp_report_req_read(hp_report_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (m->samples_count >= 24) return HP_DECODE_TOO_LONG;
            {
                hp_decode_result_t sub = hp_sample_read(&m->samples[m->samples_count], v, vn);
                if (sub != HP_DECODE_OK) return sub;
            }
            m->samples_count++;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_set_req_write(htlv_writer_t *w, const hp_set_req_t *m)
{
    if (m->has_point) {
        htlv_w_u8(w, 0x81, m->point);
    }
    if (m->has_value) {
        size_t mark = htlv_w_begin(w, 0x02);
        hp_value_write(w, &m->value);
        htlv_w_end(w, mark);
    }
}

hp_decode_result_t hp_set_req_read(hp_set_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u8(v, vn, &m->point)) return HP_DECODE_MALFORMED;
            m->has_point = true;
            break;
        case 2:
            {
                hp_decode_result_t sub = hp_value_read(&m->value, v, vn);
                if (sub != HP_DECODE_OK) return sub;
            }
            m->has_value = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_set_resp_write(htlv_writer_t *w, const hp_set_resp_t *m)
{
    if (m->has_value) {
        size_t mark = htlv_w_begin(w, 0x01);
        hp_value_write(w, &m->value);
        htlv_w_end(w, mark);
    }
}

hp_decode_result_t hp_set_resp_read(hp_set_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            {
                hp_decode_result_t sub = hp_value_read(&m->value, v, vn);
                if (sub != HP_DECODE_OK) return sub;
            }
            m->has_value = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_get_req_write(htlv_writer_t *w, const hp_get_req_t *m)
{
    for (size_t i = 0; i < m->points_count && i < 24; i++) {
        htlv_w_u8(w, 0x01, m->points[i]);
    }
}

hp_decode_result_t hp_get_req_read(hp_get_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (m->points_count >= 24) return HP_DECODE_TOO_LONG;
            if (!htlv_get_u8(v, vn, &m->points[m->points_count])) return HP_DECODE_MALFORMED;
            m->points_count++;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_get_resp_write(htlv_writer_t *w, const hp_get_resp_t *m)
{
    for (size_t i = 0; i < m->samples_count && i < 24; i++) {
        size_t mark = htlv_w_begin(w, 0x01);
        hp_sample_write(w, &m->samples[i]);
        htlv_w_end(w, mark);
    }
}

hp_decode_result_t hp_get_resp_read(hp_get_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (m->samples_count >= 24) return HP_DECODE_TOO_LONG;
            {
                hp_decode_result_t sub = hp_sample_read(&m->samples[m->samples_count], v, vn);
                if (sub != HP_DECODE_OK) return sub;
            }
            m->samples_count++;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_invoke_req_write(htlv_writer_t *w, const hp_invoke_req_t *m)
{
    if (m->has_point) {
        htlv_w_u8(w, 0x81, m->point);
    }
    if (m->has_arg) {
        htlv_w_f32(w, 0x02, m->arg);
    }
}

hp_decode_result_t hp_invoke_req_read(hp_invoke_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u8(v, vn, &m->point)) return HP_DECODE_MALFORMED;
            m->has_point = true;
            break;
        case 2:
            if (!htlv_get_f32(v, vn, &m->arg)) return HP_DECODE_MALFORMED;
            m->has_arg = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_invoke_resp_write(htlv_writer_t *w, const hp_invoke_resp_t *m)
{
    if (m->has_text) {
        htlv_w_str(w, 0x01, m->text);
    }
}

hp_decode_result_t hp_invoke_resp_read(hp_invoke_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_str(v, vn, m->text, sizeof m->text)) return HP_DECODE_TOO_LONG;
            m->has_text = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_event_req_write(htlv_writer_t *w, const hp_event_req_t *m)
{
    if (m->has_kind) {
        htlv_w_u8(w, 0x01, m->kind);
    }
    if (m->has_point) {
        htlv_w_u8(w, 0x02, m->point);
    }
    if (m->has_value) {
        size_t mark = htlv_w_begin(w, 0x03);
        hp_value_write(w, &m->value);
        htlv_w_end(w, mark);
    }
    if (m->has_text) {
        htlv_w_str(w, 0x04, m->text);
    }
    if (m->has_ts_ms) {
        htlv_w_u64(w, 0x05, m->ts_ms);
    }
}

hp_decode_result_t hp_event_req_read(hp_event_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u8(v, vn, &m->kind)) return HP_DECODE_MALFORMED;
            m->has_kind = true;
            break;
        case 2:
            if (!htlv_get_u8(v, vn, &m->point)) return HP_DECODE_MALFORMED;
            m->has_point = true;
            break;
        case 3:
            {
                hp_decode_result_t sub = hp_value_read(&m->value, v, vn);
                if (sub != HP_DECODE_OK) return sub;
            }
            m->has_value = true;
            break;
        case 4:
            if (!htlv_get_str(v, vn, m->text, sizeof m->text)) return HP_DECODE_TOO_LONG;
            m->has_text = true;
            break;
        case 5:
            if (!htlv_get_u64(v, vn, &m->ts_ms)) return HP_DECODE_MALFORMED;
            m->has_ts_ms = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_cfg_get_req_write(htlv_writer_t *w, const hp_cfg_get_req_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_cfg_get_req_read(hp_cfg_get_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_cfg_get_resp_write(htlv_writer_t *w, const hp_cfg_get_resp_t *m)
{
    if (m->has_config) {
        size_t mark = htlv_w_begin(w, 0x01);
        hp_device_config_write(w, &m->config);
        htlv_w_end(w, mark);
    }
}

hp_decode_result_t hp_cfg_get_resp_read(hp_cfg_get_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            {
                hp_decode_result_t sub = hp_device_config_read(&m->config, v, vn);
                if (sub != HP_DECODE_OK) return sub;
            }
            m->has_config = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_cfg_set_req_write(htlv_writer_t *w, const hp_cfg_set_req_t *m)
{
    if (m->has_config) {
        size_t mark = htlv_w_begin(w, 0x01);
        hp_device_config_write(w, &m->config);
        htlv_w_end(w, mark);
    }
}

hp_decode_result_t hp_cfg_set_req_read(hp_cfg_set_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            {
                hp_decode_result_t sub = hp_device_config_read(&m->config, v, vn);
                if (sub != HP_DECODE_OK) return sub;
            }
            m->has_config = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_cfg_set_resp_write(htlv_writer_t *w, const hp_cfg_set_resp_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_cfg_set_resp_read(hp_cfg_set_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_wifi_scan_req_write(htlv_writer_t *w, const hp_wifi_scan_req_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_wifi_scan_req_read(hp_wifi_scan_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_wifi_scan_resp_write(htlv_writer_t *w, const hp_wifi_scan_resp_t *m)
{
    for (size_t i = 0; i < m->networks_count && i < 20; i++) {
        size_t mark = htlv_w_begin(w, 0x01);
        hp_wifi_net_write(w, &m->networks[i]);
        htlv_w_end(w, mark);
    }
}

hp_decode_result_t hp_wifi_scan_resp_read(hp_wifi_scan_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (m->networks_count >= 20) return HP_DECODE_TOO_LONG;
            {
                hp_decode_result_t sub = hp_wifi_net_read(&m->networks[m->networks_count], v, vn);
                if (sub != HP_DECODE_OK) return sub;
            }
            m->networks_count++;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_net_status_req_write(htlv_writer_t *w, const hp_net_status_req_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_net_status_req_read(hp_net_status_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_net_status_resp_write(htlv_writer_t *w, const hp_net_status_resp_t *m)
{
    if (m->has_status) {
        size_t mark = htlv_w_begin(w, 0x01);
        hp_net_status_write(w, &m->status);
        htlv_w_end(w, mark);
    }
}

hp_decode_result_t hp_net_status_resp_read(hp_net_status_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            {
                hp_decode_result_t sub = hp_net_status_read(&m->status, v, vn);
                if (sub != HP_DECODE_OK) return sub;
            }
            m->has_status = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_ota_begin_req_write(htlv_writer_t *w, const hp_ota_begin_req_t *m)
{
    if (m->has_size) {
        htlv_w_u32(w, 0x01, m->size);
    }
    if (m->has_sha256) {
        htlv_w_bytes(w, 0x02, m->sha256, m->sha256_len);
    }
    if (m->has_version) {
        htlv_w_str(w, 0x03, m->version);
    }
    if (m->has_model) {
        htlv_w_u16(w, 0x04, m->model);
    }
}

hp_decode_result_t hp_ota_begin_req_read(hp_ota_begin_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u32(v, vn, &m->size)) return HP_DECODE_MALFORMED;
            m->has_size = true;
            break;
        case 2:
            if (vn > 32) return HP_DECODE_TOO_LONG;
            m->sha256 = v;
            m->sha256_len = vn;
            m->has_sha256 = true;
            break;
        case 3:
            if (!htlv_get_str(v, vn, m->version, sizeof m->version)) return HP_DECODE_TOO_LONG;
            m->has_version = true;
            break;
        case 4:
            if (!htlv_get_u16(v, vn, &m->model)) return HP_DECODE_MALFORMED;
            m->has_model = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_ota_begin_resp_write(htlv_writer_t *w, const hp_ota_begin_resp_t *m)
{
    if (m->has_chunk) {
        htlv_w_u16(w, 0x01, m->chunk);
    }
    if (m->has_resume_from) {
        htlv_w_u32(w, 0x02, m->resume_from);
    }
}

hp_decode_result_t hp_ota_begin_resp_read(hp_ota_begin_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u16(v, vn, &m->chunk)) return HP_DECODE_MALFORMED;
            m->has_chunk = true;
            break;
        case 2:
            if (!htlv_get_u32(v, vn, &m->resume_from)) return HP_DECODE_MALFORMED;
            m->has_resume_from = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_ota_data_req_write(htlv_writer_t *w, const hp_ota_data_req_t *m)
{
    if (m->has_offset) {
        htlv_w_u32(w, 0x01, m->offset);
    }
    if (m->has_data) {
        htlv_w_bytes(w, 0x02, m->data, m->data_len);
    }
}

hp_decode_result_t hp_ota_data_req_read(hp_ota_data_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u32(v, vn, &m->offset)) return HP_DECODE_MALFORMED;
            m->has_offset = true;
            break;
        case 2:
            if (vn > 1400) return HP_DECODE_TOO_LONG;
            m->data = v;
            m->data_len = vn;
            m->has_data = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_ota_data_resp_write(htlv_writer_t *w, const hp_ota_data_resp_t *m)
{
    if (m->has_next_offset) {
        htlv_w_u32(w, 0x01, m->next_offset);
    }
}

hp_decode_result_t hp_ota_data_resp_read(hp_ota_data_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u32(v, vn, &m->next_offset)) return HP_DECODE_MALFORMED;
            m->has_next_offset = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_ota_end_req_write(htlv_writer_t *w, const hp_ota_end_req_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_ota_end_req_read(hp_ota_end_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_ota_end_resp_write(htlv_writer_t *w, const hp_ota_end_resp_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_ota_end_resp_read(hp_ota_end_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_ota_abort_req_write(htlv_writer_t *w, const hp_ota_abort_req_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_ota_abort_req_read(hp_ota_abort_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_ota_abort_resp_write(htlv_writer_t *w, const hp_ota_abort_resp_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_ota_abort_resp_read(hp_ota_abort_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_ota_status_req_write(htlv_writer_t *w, const hp_ota_status_req_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_ota_status_req_read(hp_ota_status_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_ota_status_resp_write(htlv_writer_t *w, const hp_ota_status_resp_t *m)
{
    if (m->has_state) {
        htlv_w_u8(w, 0x01, m->state);
    }
    if (m->has_received) {
        htlv_w_u32(w, 0x02, m->received);
    }
    if (m->has_error) {
        htlv_w_u8(w, 0x03, m->error);
    }
}

hp_decode_result_t hp_ota_status_resp_read(hp_ota_status_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u8(v, vn, &m->state)) return HP_DECODE_MALFORMED;
            m->has_state = true;
            break;
        case 2:
            if (!htlv_get_u32(v, vn, &m->received)) return HP_DECODE_MALFORMED;
            m->has_received = true;
            break;
        case 3:
            if (!htlv_get_u8(v, vn, &m->error)) return HP_DECODE_MALFORMED;
            m->has_error = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_ota_confirm_req_write(htlv_writer_t *w, const hp_ota_confirm_req_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_ota_confirm_req_read(hp_ota_confirm_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_ota_confirm_resp_write(htlv_writer_t *w, const hp_ota_confirm_resp_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_ota_confirm_resp_read(hp_ota_confirm_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_reboot_req_write(htlv_writer_t *w, const hp_reboot_req_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_reboot_req_read(hp_reboot_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_reboot_resp_write(htlv_writer_t *w, const hp_reboot_resp_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_reboot_resp_read(hp_reboot_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_factory_reset_req_write(htlv_writer_t *w, const hp_factory_reset_req_t *m)
{
    if (m->has_mode) {
        htlv_w_u8(w, 0x01, m->mode);
    }
}

hp_decode_result_t hp_factory_reset_req_read(hp_factory_reset_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u8(v, vn, &m->mode)) return HP_DECODE_MALFORMED;
            m->has_mode = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_factory_reset_resp_write(htlv_writer_t *w, const hp_factory_reset_resp_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_factory_reset_resp_read(hp_factory_reset_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_identify_req_write(htlv_writer_t *w, const hp_identify_req_t *m)
{
    if (m->has_seconds) {
        htlv_w_u8(w, 0x01, m->seconds);
    }
}

hp_decode_result_t hp_identify_req_read(hp_identify_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u8(v, vn, &m->seconds)) return HP_DECODE_MALFORMED;
            m->has_seconds = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_identify_resp_write(htlv_writer_t *w, const hp_identify_resp_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_identify_resp_read(hp_identify_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_log_req_write(htlv_writer_t *w, const hp_log_req_t *m)
{
    if (m->has_level) {
        htlv_w_u8(w, 0x01, m->level);
    }
    if (m->has_tag) {
        htlv_w_str(w, 0x02, m->tag);
    }
    if (m->has_text) {
        htlv_w_str(w, 0x03, m->text);
    }
    if (m->has_ts_ms) {
        htlv_w_u64(w, 0x04, m->ts_ms);
    }
}

hp_decode_result_t hp_log_req_read(hp_log_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u8(v, vn, &m->level)) return HP_DECODE_MALFORMED;
            m->has_level = true;
            break;
        case 2:
            if (!htlv_get_str(v, vn, m->tag, sizeof m->tag)) return HP_DECODE_TOO_LONG;
            m->has_tag = true;
            break;
        case 3:
            if (!htlv_get_str(v, vn, m->text, sizeof m->text)) return HP_DECODE_TOO_LONG;
            m->has_text = true;
            break;
        case 4:
            if (!htlv_get_u64(v, vn, &m->ts_ms)) return HP_DECODE_MALFORMED;
            m->has_ts_ms = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_pair_code_req_write(htlv_writer_t *w, const hp_pair_code_req_t *m)
{
    if (m->has_code) {
        htlv_w_u16(w, 0x01, m->code);
    }
}

hp_decode_result_t hp_pair_code_req_read(hp_pair_code_req_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        case 1:
            if (!htlv_get_u16(v, vn, &m->code)) return HP_DECODE_MALFORMED;
            m->has_code = true;
            break;
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

void hp_pair_code_resp_write(htlv_writer_t *w, const hp_pair_code_resp_t *m)
{
    (void)w;
    (void)m;
}

hp_decode_result_t hp_pair_code_resp_read(hp_pair_code_resp_t *m, const uint8_t *p, size_t n)
{
    memset(m, 0, sizeof *m);
    htlv_reader_t r;
    htlv_r_init(&r, p, n);
    uint8_t tag;
    const uint8_t *v;
    size_t vn;
    htlv_result_t res;
    while ((res = htlv_r_next(&r, &tag, &v, &vn)) == HTLV_OK) {
        switch (tag & 0x7F) {
        default:
            if (tag & 0x80) return HP_DECODE_UNSUPPORTED;
            break;
        }
    }
    return res == HTLV_END ? HP_DECODE_OK : HP_DECODE_MALFORMED;
}

