// GENERATED by home-protocol/gen from schema.yaml — do not edit.
export const PROTO_MAJOR = 1;
export const PROTO_MINOR = 0;

export const Flags = {
  RESP: 1,
  ERR: 2,
  NOACK: 4,
} as const;
export type Flags = (typeof Flags)[keyof typeof Flags];

export const ErrorCode = {
  OK: 0,
  UNSUPPORTED: 1,
  BAD_REQUEST: 2,
  NOT_FOUND: 3,
  FORBIDDEN: 4,
  BUSY: 5,
  INVALID_VALUE: 6,
  OTA_BAD_IMAGE: 7,
  OTA_HASH_MISMATCH: 8,
  OTA_WRONG_MODEL: 9,
  STORAGE: 10,
  SENSOR: 11,
  INTERNAL: 12,
  TIMEOUT: 13,
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const Model = {
  UNKNOWN: 0,
  CO2_EGG: 1,
  RELAY: 2,
  BOARD_PROBE: 32512,
} as const;
export type Model = (typeof Model)[keyof typeof Model];

export const PointKind = {
  SENSOR: 0,
  ACTUATOR: 1,
  SETTING: 2,
  ACTION: 3,
} as const;
export type PointKind = (typeof PointKind)[keyof typeof PointKind];

export const PointType = {
  BOOL: 0,
  I32: 1,
  F32: 2,
  STR: 3,
  ENUM: 4,
} as const;
export type PointType = (typeof PointType)[keyof typeof PointType];

export const UiHint = {
  AUTO: 0,
  GAUGE: 1,
  SWITCH: 2,
  SLIDER: 3,
  BUTTON: 4,
  SELECT: 5,
  TEXT: 6,
  HIDDEN: 7,
} as const;
export type UiHint = (typeof UiHint)[keyof typeof UiHint];

export const PointFlags = {
  HISTORY: 1,
  READONLY: 2,
  ADVANCED: 4,
  PERSIST: 8,
} as const;
export type PointFlags = (typeof PointFlags)[keyof typeof PointFlags];

export const ResetMode = {
  SETTINGS: 1,
  FIRMWARE: 2,
  ALL: 3,
} as const;
export type ResetMode = (typeof ResetMode)[keyof typeof ResetMode];

export const BootPartition = {
  FACTORY: 0,
  OTA0: 1,
  OTA1: 2,
  UNKNOWN: 255,
} as const;
export type BootPartition = (typeof BootPartition)[keyof typeof BootPartition];

export const AdoptState = {
  NEW: 0,
  ADOPTED: 1,
  BLOCKED: 2,
} as const;
export type AdoptState = (typeof AdoptState)[keyof typeof AdoptState];

export const IpMode = {
  DHCP: 0,
  STATIC: 1,
} as const;
export type IpMode = (typeof IpMode)[keyof typeof IpMode];

export const BleMode = {
  ALWAYS: 0,
  BUTTON: 1,
  OFF: 2,
} as const;
export type BleMode = (typeof BleMode)[keyof typeof BleMode];

export const LogLevel = {
  NONE: 0,
  ERROR: 1,
  WARN: 2,
  INFO: 3,
  DEBUG: 4,
  VERBOSE: 5,
} as const;
export type LogLevel = (typeof LogLevel)[keyof typeof LogLevel];

export const WifiAuth = {
  OPEN: 0,
  WEP: 1,
  WPA: 2,
  WPA2: 3,
  WPA3: 4,
  OTHER: 5,
} as const;
export type WifiAuth = (typeof WifiAuth)[keyof typeof WifiAuth];

export const LinkState = {
  NO_CONFIG: 0,
  WIFI_CONNECTING: 1,
  IP_OK: 2,
  SERVER_CONNECTING: 3,
  ONLINE: 4,
} as const;
export type LinkState = (typeof LinkState)[keyof typeof LinkState];

export const OtaState = {
  IDLE: 0,
  RECEIVING: 1,
  VERIFYING: 2,
  DONE: 3,
  FAILED: 4,
} as const;
export type OtaState = (typeof OtaState)[keyof typeof OtaState];

export const EventKind = {
  BOOT: 1,
  BUTTON: 2,
  THRESHOLD: 3,
  SENSOR_ERROR: 4,
  PREHEAT_DONE: 5,
} as const;
export type EventKind = (typeof EventKind)[keyof typeof EventKind];

export const MsgType = {
  HELLO: 0x01,
  PING: 0x03,
  DESCRIBE: 0x10,
  STATE: 0x11,
  REPORT: 0x12,
  SET: 0x13,
  GET: 0x14,
  INVOKE: 0x15,
  EVENT: 0x16,
  CFG_GET: 0x20,
  CFG_SET: 0x21,
  WIFI_SCAN: 0x22,
  NET_STATUS: 0x23,
  OTA_BEGIN: 0x30,
  OTA_DATA: 0x31,
  OTA_END: 0x32,
  OTA_ABORT: 0x33,
  OTA_STATUS: 0x34,
  OTA_CONFIRM: 0x35,
  REBOOT: 0x40,
  FACTORY_RESET: 0x41,
  IDENTIFY: 0x42,
  LOG: 0x50,
  PAIR_CODE: 0x60,
} as const;
