// GENERATED by home-protocol/gen from schema.yaml — do not edit.
@file:Suppress("unused", "RedundantVisibilityModifier")

package home.protocol

object Proto {
    const val MAJOR = 1
    const val MINOR = 0
    const val HEADER_VERSION = 1
    const val HEADER_SIZE = 6
    const val MAX_MESSAGE = 2048
    const val TCP_PORT = 7700
    const val DISCOVER_PORT = 7701
    const val MDNS_SERVICE = "_home._tcp"
    const val BLE_SERVICE_UUID = "6e6f6d65-0001-4c9e-9a6e-686f6d650001"
    const val BLE_RX_UUID = "6e6f6d65-0002-4c9e-9a6e-686f6d650001"
    const val BLE_TX_UUID = "6e6f6d65-0003-4c9e-9a6e-686f6d650001"
    const val BLE_INFO_UUID = "6e6f6d65-0004-4c9e-9a6e-686f6d650001"
    const val BLE_MANUFACTURER_ID = 65535
    const val OTA_CHUNK = 1024
    const val OTA_WINDOW = 8
}

object Flags {
    const val RESP = 1
    const val ERR = 2
    const val NOACK = 4
    fun name(v: Int): String = when (v) {
        1 -> "RESP"
        2 -> "ERR"
        4 -> "NOACK"
        else -> v.toString()
    }
}

object ErrorCode {
    const val OK = 0
    const val UNSUPPORTED = 1
    const val BAD_REQUEST = 2
    const val NOT_FOUND = 3
    const val FORBIDDEN = 4
    const val BUSY = 5
    const val INVALID_VALUE = 6
    const val OTA_BAD_IMAGE = 7
    const val OTA_HASH_MISMATCH = 8
    const val OTA_WRONG_MODEL = 9
    const val STORAGE = 10
    const val SENSOR = 11
    const val INTERNAL = 12
    const val TIMEOUT = 13
    fun name(v: Int): String = when (v) {
        0 -> "OK"
        1 -> "UNSUPPORTED"
        2 -> "BAD_REQUEST"
        3 -> "NOT_FOUND"
        4 -> "FORBIDDEN"
        5 -> "BUSY"
        6 -> "INVALID_VALUE"
        7 -> "OTA_BAD_IMAGE"
        8 -> "OTA_HASH_MISMATCH"
        9 -> "OTA_WRONG_MODEL"
        10 -> "STORAGE"
        11 -> "SENSOR"
        12 -> "INTERNAL"
        13 -> "TIMEOUT"
        else -> v.toString()
    }
}

object Model {
    const val UNKNOWN = 0
    const val CO2_EGG = 1
    const val RELAY = 2
    const val BOARD_PROBE = 32512
    fun name(v: Int): String = when (v) {
        0 -> "UNKNOWN"
        1 -> "CO2_EGG"
        2 -> "RELAY"
        32512 -> "BOARD_PROBE"
        else -> v.toString()
    }
}

object PointKind {
    const val SENSOR = 0
    const val ACTUATOR = 1
    const val SETTING = 2
    const val ACTION = 3
    fun name(v: Int): String = when (v) {
        0 -> "SENSOR"
        1 -> "ACTUATOR"
        2 -> "SETTING"
        3 -> "ACTION"
        else -> v.toString()
    }
}

object PointType {
    const val BOOL = 0
    const val I32 = 1
    const val F32 = 2
    const val STR = 3
    const val ENUM = 4
    fun name(v: Int): String = when (v) {
        0 -> "BOOL"
        1 -> "I32"
        2 -> "F32"
        3 -> "STR"
        4 -> "ENUM"
        else -> v.toString()
    }
}

object UiHint {
    const val AUTO = 0
    const val GAUGE = 1
    const val SWITCH = 2
    const val SLIDER = 3
    const val BUTTON = 4
    const val SELECT = 5
    const val TEXT = 6
    const val HIDDEN = 7
    fun name(v: Int): String = when (v) {
        0 -> "AUTO"
        1 -> "GAUGE"
        2 -> "SWITCH"
        3 -> "SLIDER"
        4 -> "BUTTON"
        5 -> "SELECT"
        6 -> "TEXT"
        7 -> "HIDDEN"
        else -> v.toString()
    }
}

object PointFlags {
    const val HISTORY = 1
    const val READONLY = 2
    const val ADVANCED = 4
    const val PERSIST = 8
    fun name(v: Int): String = when (v) {
        1 -> "HISTORY"
        2 -> "READONLY"
        4 -> "ADVANCED"
        8 -> "PERSIST"
        else -> v.toString()
    }
}

object ResetMode {
    const val SETTINGS = 1
    const val FIRMWARE = 2
    const val ALL = 3
    fun name(v: Int): String = when (v) {
        1 -> "SETTINGS"
        2 -> "FIRMWARE"
        3 -> "ALL"
        else -> v.toString()
    }
}

object BootPartition {
    const val FACTORY = 0
    const val OTA0 = 1
    const val OTA1 = 2
    const val UNKNOWN = 255
    fun name(v: Int): String = when (v) {
        0 -> "FACTORY"
        1 -> "OTA0"
        2 -> "OTA1"
        255 -> "UNKNOWN"
        else -> v.toString()
    }
}

object AdoptState {
    const val NEW = 0
    const val ADOPTED = 1
    const val BLOCKED = 2
    fun name(v: Int): String = when (v) {
        0 -> "NEW"
        1 -> "ADOPTED"
        2 -> "BLOCKED"
        else -> v.toString()
    }
}

object IpMode {
    const val DHCP = 0
    const val STATIC = 1
    fun name(v: Int): String = when (v) {
        0 -> "DHCP"
        1 -> "STATIC"
        else -> v.toString()
    }
}

object BleMode {
    const val ALWAYS = 0
    const val BUTTON = 1
    const val OFF = 2
    fun name(v: Int): String = when (v) {
        0 -> "ALWAYS"
        1 -> "BUTTON"
        2 -> "OFF"
        else -> v.toString()
    }
}

object LogLevel {
    const val NONE = 0
    const val ERROR = 1
    const val WARN = 2
    const val INFO = 3
    const val DEBUG = 4
    const val VERBOSE = 5
    fun name(v: Int): String = when (v) {
        0 -> "NONE"
        1 -> "ERROR"
        2 -> "WARN"
        3 -> "INFO"
        4 -> "DEBUG"
        5 -> "VERBOSE"
        else -> v.toString()
    }
}

object WifiAuth {
    const val OPEN = 0
    const val WEP = 1
    const val WPA = 2
    const val WPA2 = 3
    const val WPA3 = 4
    const val OTHER = 5
    fun name(v: Int): String = when (v) {
        0 -> "OPEN"
        1 -> "WEP"
        2 -> "WPA"
        3 -> "WPA2"
        4 -> "WPA3"
        5 -> "OTHER"
        else -> v.toString()
    }
}

object LinkState {
    const val NO_CONFIG = 0
    const val WIFI_CONNECTING = 1
    const val IP_OK = 2
    const val SERVER_CONNECTING = 3
    const val ONLINE = 4
    fun name(v: Int): String = when (v) {
        0 -> "NO_CONFIG"
        1 -> "WIFI_CONNECTING"
        2 -> "IP_OK"
        3 -> "SERVER_CONNECTING"
        4 -> "ONLINE"
        else -> v.toString()
    }
}

object OtaState {
    const val IDLE = 0
    const val RECEIVING = 1
    const val VERIFYING = 2
    const val DONE = 3
    const val FAILED = 4
    fun name(v: Int): String = when (v) {
        0 -> "IDLE"
        1 -> "RECEIVING"
        2 -> "VERIFYING"
        3 -> "DONE"
        4 -> "FAILED"
        else -> v.toString()
    }
}

object EventKind {
    const val BOOT = 1
    const val BUTTON = 2
    const val THRESHOLD = 3
    const val SENSOR_ERROR = 4
    const val PREHEAT_DONE = 5
    fun name(v: Int): String = when (v) {
        1 -> "BOOT"
        2 -> "BUTTON"
        3 -> "THRESHOLD"
        4 -> "SENSOR_ERROR"
        5 -> "PREHEAT_DONE"
        else -> v.toString()
    }
}

object MsgType {
    const val HELLO = 0x01
    const val PING = 0x03
    const val DESCRIBE = 0x10
    const val STATE = 0x11
    const val REPORT = 0x12
    const val SET = 0x13
    const val GET = 0x14
    const val INVOKE = 0x15
    const val EVENT = 0x16
    const val CFG_GET = 0x20
    const val CFG_SET = 0x21
    const val WIFI_SCAN = 0x22
    const val NET_STATUS = 0x23
    const val OTA_BEGIN = 0x30
    const val OTA_DATA = 0x31
    const val OTA_END = 0x32
    const val OTA_ABORT = 0x33
    const val OTA_STATUS = 0x34
    const val OTA_CONFIRM = 0x35
    const val REBOOT = 0x40
    const val FACTORY_RESET = 0x41
    const val IDENTIFY = 0x42
    const val LOG = 0x50
    const val PAIR_CODE = 0x60
}

class Value : ProtoBody {
    var b: Boolean? = null
    var i: Int? = null
    var f: Float? = null
    var s: String? = null

    override fun write(w: TlvWriter) {
        b?.let { w.bool(0x01, it) }
        i?.let { w.i32(0x02, it) }
        f?.let { w.f32(0x03, it) }
        s?.let { w.str(0x04, it, 64) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): Value {
            val m = Value()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.b = r.bool()
                    2 -> m.i = r.i32()
                    3 -> m.f = r.f32()
                    4 -> m.s = r.str()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class PointDef : ProtoBody {
    var id: Int? = null
    var key: String? = null
    var title: String? = null
    var kind: Int? = null
    var type: Int? = null
    var unit: String? = null
    var min: Float? = null
    var max: Float? = null
    var step: Float? = null
    var options: MutableList<String> = mutableListOf()
    var ui: Int? = null
    var flags: Int? = null
    var thrWarn: Float? = null
    var thrAlarm: Float? = null
    var hasArg: Boolean? = null
    var argDefault: Float? = null

    override fun write(w: TlvWriter) {
        id?.let { w.u8(0x81, it) }
        key?.let { w.str(0x02, it, 24) }
        title?.let { w.str(0x03, it, 48) }
        kind?.let { w.u8(0x04, it) }
        type?.let { w.u8(0x05, it) }
        unit?.let { w.str(0x06, it, 8) }
        min?.let { w.f32(0x07, it) }
        max?.let { w.f32(0x08, it) }
        step?.let { w.f32(0x09, it) }
        if (options.size > 8) throw ProtoException(ErrorCode.INVALID_VALUE, "PointDef.options: more than 8 items")
        for (x in options) w.str(0x0A, x, 16)
        ui?.let { w.u8(0x0B, it) }
        flags?.let { w.u8(0x0C, it) }
        thrWarn?.let { w.f32(0x0D, it) }
        thrAlarm?.let { w.f32(0x0E, it) }
        hasArg?.let { w.bool(0x0F, it) }
        argDefault?.let { w.f32(0x10, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): PointDef {
            val m = PointDef()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.id = r.u8()
                    2 -> m.key = r.str()
                    3 -> m.title = r.str()
                    4 -> m.kind = r.u8()
                    5 -> m.type = r.u8()
                    6 -> m.unit = r.str()
                    7 -> m.min = r.f32()
                    8 -> m.max = r.f32()
                    9 -> m.step = r.f32()
                    10 -> m.options.add(r.str())
                    11 -> m.ui = r.u8()
                    12 -> m.flags = r.u8()
                    13 -> m.thrWarn = r.f32()
                    14 -> m.thrAlarm = r.f32()
                    15 -> m.hasArg = r.bool()
                    16 -> m.argDefault = r.f32()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class Sample : ProtoBody {
    var point: Int? = null
    var value: Value? = null
    var tsMs: Long? = null

    override fun write(w: TlvWriter) {
        point?.let { w.u8(0x81, it) }
        value?.let { w.struct(0x02, it) }
        tsMs?.let { w.u64(0x03, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): Sample {
            val m = Sample()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.point = r.u8()
                    2 -> m.value = r.struct(Value::read)
                    3 -> m.tsMs = r.u64()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class WifiNet : ProtoBody {
    var ssid: String? = null
    var rssi: Int? = null
    var auth: Int? = null
    var channel: Int? = null

    override fun write(w: TlvWriter) {
        ssid?.let { w.str(0x01, it, 32) }
        rssi?.let { w.i32(0x02, it) }
        auth?.let { w.u8(0x03, it) }
        channel?.let { w.u8(0x04, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): WifiNet {
            val m = WifiNet()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.ssid = r.str()
                    2 -> m.rssi = r.i32()
                    3 -> m.auth = r.u8()
                    4 -> m.channel = r.u8()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class NetConfig : ProtoBody {
    var ipMode: Int? = null
    var ip: Long? = null
    var mask: Long? = null
    var gw: Long? = null
    var dns1: Long? = null
    var dns2: Long? = null
    var hostname: String? = null

    override fun write(w: TlvWriter) {
        ipMode?.let { w.u8(0x01, it) }
        ip?.let { w.u32(0x02, it) }
        mask?.let { w.u32(0x03, it) }
        gw?.let { w.u32(0x04, it) }
        dns1?.let { w.u32(0x05, it) }
        dns2?.let { w.u32(0x06, it) }
        hostname?.let { w.str(0x07, it, 32) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): NetConfig {
            val m = NetConfig()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.ipMode = r.u8()
                    2 -> m.ip = r.u32()
                    3 -> m.mask = r.u32()
                    4 -> m.gw = r.u32()
                    5 -> m.dns1 = r.u32()
                    6 -> m.dns2 = r.u32()
                    7 -> m.hostname = r.str()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class DeviceConfig : ProtoBody {
    var name: String? = null
    var room: String? = null
    var wifiSsid: String? = null
    var wifiPass: String? = null
    var net: NetConfig? = null
    var serverHost: String? = null
    var serverPort: Int? = null
    var bleMode: Int? = null
    var logLevel: Int? = null

    override fun write(w: TlvWriter) {
        name?.let { w.str(0x01, it, 48) }
        room?.let { w.str(0x02, it, 48) }
        wifiSsid?.let { w.str(0x03, it, 32) }
        wifiPass?.let { w.str(0x04, it, 64) }
        net?.let { w.struct(0x05, it) }
        serverHost?.let { w.str(0x06, it, 64) }
        serverPort?.let { w.u16(0x07, it) }
        bleMode?.let { w.u8(0x08, it) }
        logLevel?.let { w.u8(0x09, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): DeviceConfig {
            val m = DeviceConfig()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.name = r.str()
                    2 -> m.room = r.str()
                    3 -> m.wifiSsid = r.str()
                    4 -> m.wifiPass = r.str()
                    5 -> m.net = r.struct(NetConfig::read)
                    6 -> m.serverHost = r.str()
                    7 -> m.serverPort = r.u16()
                    8 -> m.bleMode = r.u8()
                    9 -> m.logLevel = r.u8()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class NetStatus : ProtoBody {
    var state: Int? = null
    var current: NetConfig? = null
    var rssi: Int? = null
    var ssid: String? = null
    var server: String? = null
    var mac: String? = null

    override fun write(w: TlvWriter) {
        state?.let { w.u8(0x01, it) }
        current?.let { w.struct(0x02, it) }
        rssi?.let { w.i32(0x03, it) }
        ssid?.let { w.str(0x04, it, 32) }
        server?.let { w.str(0x05, it, 64) }
        mac?.let { w.str(0x06, it, 17) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): NetStatus {
            val m = NetStatus()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.state = r.u8()
                    2 -> m.current = r.struct(NetConfig::read)
                    3 -> m.rssi = r.i32()
                    4 -> m.ssid = r.str()
                    5 -> m.server = r.str()
                    6 -> m.mac = r.str()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class ErrorBody : ProtoBody {
    var code: Int? = null
    var text: String? = null

    override fun write(w: TlvWriter) {
        code?.let { w.u8(0x01, it) }
        text?.let { w.str(0x02, it, 96) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): ErrorBody {
            val m = ErrorBody()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.code = r.u8()
                    2 -> m.text = r.str()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class HelloReq : ProtoMessage {
    override val msgType: Int get() = MsgType.HELLO
    override val isResponse: Boolean get() = false
    var deviceId: String? = null
    var model: Int? = null
    var hwRev: Int? = null
    var fwVersion: String? = null
    var protoMajor: Int? = null
    var protoMinor: Int? = null
    var bootPartition: Int? = null
    var resetReason: Int? = null
    var uptimeS: Long? = null
    var name: String? = null
    var idfVersion: String? = null
    var pendingVerify: Boolean? = null

    override fun write(w: TlvWriter) {
        deviceId?.let { w.str(0x81, it, 12) }
        model?.let { w.u16(0x02, it) }
        hwRev?.let { w.u8(0x03, it) }
        fwVersion?.let { w.str(0x04, it, 32) }
        protoMajor?.let { w.u8(0x05, it) }
        protoMinor?.let { w.u8(0x06, it) }
        bootPartition?.let { w.u8(0x07, it) }
        resetReason?.let { w.u8(0x08, it) }
        uptimeS?.let { w.u32(0x09, it) }
        name?.let { w.str(0x0A, it, 48) }
        idfVersion?.let { w.str(0x0B, it, 32) }
        pendingVerify?.let { w.bool(0x0C, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): HelloReq {
            val m = HelloReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.deviceId = r.str()
                    2 -> m.model = r.u16()
                    3 -> m.hwRev = r.u8()
                    4 -> m.fwVersion = r.str()
                    5 -> m.protoMajor = r.u8()
                    6 -> m.protoMinor = r.u8()
                    7 -> m.bootPartition = r.u8()
                    8 -> m.resetReason = r.u8()
                    9 -> m.uptimeS = r.u32()
                    10 -> m.name = r.str()
                    11 -> m.idfVersion = r.str()
                    12 -> m.pendingVerify = r.bool()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class HelloResp : ProtoMessage {
    override val msgType: Int get() = MsgType.HELLO
    override val isResponse: Boolean get() = true
    var timeMs: Long? = null
    var state: Int? = null
    var logLevel: Int? = null

    override fun write(w: TlvWriter) {
        timeMs?.let { w.u64(0x01, it) }
        state?.let { w.u8(0x02, it) }
        logLevel?.let { w.u8(0x03, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): HelloResp {
            val m = HelloResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.timeMs = r.u64()
                    2 -> m.state = r.u8()
                    3 -> m.logLevel = r.u8()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class PingReq : ProtoMessage {
    override val msgType: Int get() = MsgType.PING
    override val isResponse: Boolean get() = false
    var timeMs: Long? = null

    override fun write(w: TlvWriter) {
        timeMs?.let { w.u64(0x01, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): PingReq {
            val m = PingReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.timeMs = r.u64()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class PingResp : ProtoMessage {
    override val msgType: Int get() = MsgType.PING
    override val isResponse: Boolean get() = true
    var timeMs: Long? = null

    override fun write(w: TlvWriter) {
        timeMs?.let { w.u64(0x01, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): PingResp {
            val m = PingResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.timeMs = r.u64()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class DescribeReq : ProtoMessage {
    override val msgType: Int get() = MsgType.DESCRIBE
    override val isResponse: Boolean get() = false

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): DescribeReq {
            val m = DescribeReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class DescribeResp : ProtoMessage {
    override val msgType: Int get() = MsgType.DESCRIBE
    override val isResponse: Boolean get() = true
    var points: MutableList<PointDef> = mutableListOf()

    override fun write(w: TlvWriter) {
        if (points.size > 24) throw ProtoException(ErrorCode.INVALID_VALUE, "DescribeResp.points: more than 24 items")
        for (x in points) w.struct(0x01, x)
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): DescribeResp {
            val m = DescribeResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.points.add(r.struct(PointDef::read))
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class StateReq : ProtoMessage {
    override val msgType: Int get() = MsgType.STATE
    override val isResponse: Boolean get() = false
    var samples: MutableList<Sample> = mutableListOf()

    override fun write(w: TlvWriter) {
        if (samples.size > 24) throw ProtoException(ErrorCode.INVALID_VALUE, "StateReq.samples: more than 24 items")
        for (x in samples) w.struct(0x01, x)
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): StateReq {
            val m = StateReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.samples.add(r.struct(Sample::read))
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class ReportReq : ProtoMessage {
    override val msgType: Int get() = MsgType.REPORT
    override val isResponse: Boolean get() = false
    var samples: MutableList<Sample> = mutableListOf()

    override fun write(w: TlvWriter) {
        if (samples.size > 24) throw ProtoException(ErrorCode.INVALID_VALUE, "ReportReq.samples: more than 24 items")
        for (x in samples) w.struct(0x01, x)
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): ReportReq {
            val m = ReportReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.samples.add(r.struct(Sample::read))
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class SetReq : ProtoMessage {
    override val msgType: Int get() = MsgType.SET
    override val isResponse: Boolean get() = false
    var point: Int? = null
    var value: Value? = null

    override fun write(w: TlvWriter) {
        point?.let { w.u8(0x81, it) }
        value?.let { w.struct(0x02, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): SetReq {
            val m = SetReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.point = r.u8()
                    2 -> m.value = r.struct(Value::read)
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class SetResp : ProtoMessage {
    override val msgType: Int get() = MsgType.SET
    override val isResponse: Boolean get() = true
    var value: Value? = null

    override fun write(w: TlvWriter) {
        value?.let { w.struct(0x01, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): SetResp {
            val m = SetResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.value = r.struct(Value::read)
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class GetReq : ProtoMessage {
    override val msgType: Int get() = MsgType.GET
    override val isResponse: Boolean get() = false
    var points: MutableList<Int> = mutableListOf()

    override fun write(w: TlvWriter) {
        if (points.size > 24) throw ProtoException(ErrorCode.INVALID_VALUE, "GetReq.points: more than 24 items")
        for (x in points) w.u8(0x01, x)
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): GetReq {
            val m = GetReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.points.add(r.u8())
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class GetResp : ProtoMessage {
    override val msgType: Int get() = MsgType.GET
    override val isResponse: Boolean get() = true
    var samples: MutableList<Sample> = mutableListOf()

    override fun write(w: TlvWriter) {
        if (samples.size > 24) throw ProtoException(ErrorCode.INVALID_VALUE, "GetResp.samples: more than 24 items")
        for (x in samples) w.struct(0x01, x)
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): GetResp {
            val m = GetResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.samples.add(r.struct(Sample::read))
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class InvokeReq : ProtoMessage {
    override val msgType: Int get() = MsgType.INVOKE
    override val isResponse: Boolean get() = false
    var point: Int? = null
    var arg: Float? = null

    override fun write(w: TlvWriter) {
        point?.let { w.u8(0x81, it) }
        arg?.let { w.f32(0x02, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): InvokeReq {
            val m = InvokeReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.point = r.u8()
                    2 -> m.arg = r.f32()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class InvokeResp : ProtoMessage {
    override val msgType: Int get() = MsgType.INVOKE
    override val isResponse: Boolean get() = true
    var text: String? = null

    override fun write(w: TlvWriter) {
        text?.let { w.str(0x01, it, 96) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): InvokeResp {
            val m = InvokeResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.text = r.str()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class EventReq : ProtoMessage {
    override val msgType: Int get() = MsgType.EVENT
    override val isResponse: Boolean get() = false
    var kind: Int? = null
    var point: Int? = null
    var value: Value? = null
    var text: String? = null
    var tsMs: Long? = null

    override fun write(w: TlvWriter) {
        kind?.let { w.u8(0x01, it) }
        point?.let { w.u8(0x02, it) }
        value?.let { w.struct(0x03, it) }
        text?.let { w.str(0x04, it, 96) }
        tsMs?.let { w.u64(0x05, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): EventReq {
            val m = EventReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.kind = r.u8()
                    2 -> m.point = r.u8()
                    3 -> m.value = r.struct(Value::read)
                    4 -> m.text = r.str()
                    5 -> m.tsMs = r.u64()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class CfgGetReq : ProtoMessage {
    override val msgType: Int get() = MsgType.CFG_GET
    override val isResponse: Boolean get() = false

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): CfgGetReq {
            val m = CfgGetReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class CfgGetResp : ProtoMessage {
    override val msgType: Int get() = MsgType.CFG_GET
    override val isResponse: Boolean get() = true
    var config: DeviceConfig? = null

    override fun write(w: TlvWriter) {
        config?.let { w.struct(0x01, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): CfgGetResp {
            val m = CfgGetResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.config = r.struct(DeviceConfig::read)
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class CfgSetReq : ProtoMessage {
    override val msgType: Int get() = MsgType.CFG_SET
    override val isResponse: Boolean get() = false
    var config: DeviceConfig? = null

    override fun write(w: TlvWriter) {
        config?.let { w.struct(0x01, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): CfgSetReq {
            val m = CfgSetReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.config = r.struct(DeviceConfig::read)
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class CfgSetResp : ProtoMessage {
    override val msgType: Int get() = MsgType.CFG_SET
    override val isResponse: Boolean get() = true

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): CfgSetResp {
            val m = CfgSetResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class WifiScanReq : ProtoMessage {
    override val msgType: Int get() = MsgType.WIFI_SCAN
    override val isResponse: Boolean get() = false

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): WifiScanReq {
            val m = WifiScanReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class WifiScanResp : ProtoMessage {
    override val msgType: Int get() = MsgType.WIFI_SCAN
    override val isResponse: Boolean get() = true
    var networks: MutableList<WifiNet> = mutableListOf()

    override fun write(w: TlvWriter) {
        if (networks.size > 20) throw ProtoException(ErrorCode.INVALID_VALUE, "WifiScanResp.networks: more than 20 items")
        for (x in networks) w.struct(0x01, x)
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): WifiScanResp {
            val m = WifiScanResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.networks.add(r.struct(WifiNet::read))
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class NetStatusReq : ProtoMessage {
    override val msgType: Int get() = MsgType.NET_STATUS
    override val isResponse: Boolean get() = false

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): NetStatusReq {
            val m = NetStatusReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class NetStatusResp : ProtoMessage {
    override val msgType: Int get() = MsgType.NET_STATUS
    override val isResponse: Boolean get() = true
    var status: NetStatus? = null

    override fun write(w: TlvWriter) {
        status?.let { w.struct(0x01, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): NetStatusResp {
            val m = NetStatusResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.status = r.struct(NetStatus::read)
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class OtaBeginReq : ProtoMessage {
    override val msgType: Int get() = MsgType.OTA_BEGIN
    override val isResponse: Boolean get() = false
    var size: Long? = null
    var sha256: ByteArray? = null
    var version: String? = null
    var model: Int? = null

    override fun write(w: TlvWriter) {
        size?.let { w.u32(0x01, it) }
        sha256?.let { w.bytes(0x02, it, 32) }
        version?.let { w.str(0x03, it, 32) }
        model?.let { w.u16(0x04, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): OtaBeginReq {
            val m = OtaBeginReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.size = r.u32()
                    2 -> m.sha256 = r.bytes()
                    3 -> m.version = r.str()
                    4 -> m.model = r.u16()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class OtaBeginResp : ProtoMessage {
    override val msgType: Int get() = MsgType.OTA_BEGIN
    override val isResponse: Boolean get() = true
    var chunk: Int? = null
    var resumeFrom: Long? = null

    override fun write(w: TlvWriter) {
        chunk?.let { w.u16(0x01, it) }
        resumeFrom?.let { w.u32(0x02, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): OtaBeginResp {
            val m = OtaBeginResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.chunk = r.u16()
                    2 -> m.resumeFrom = r.u32()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class OtaDataReq : ProtoMessage {
    override val msgType: Int get() = MsgType.OTA_DATA
    override val isResponse: Boolean get() = false
    var offset: Long? = null
    var data: ByteArray? = null

    override fun write(w: TlvWriter) {
        offset?.let { w.u32(0x01, it) }
        data?.let { w.bytes(0x02, it, 1400) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): OtaDataReq {
            val m = OtaDataReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.offset = r.u32()
                    2 -> m.data = r.bytes()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class OtaDataResp : ProtoMessage {
    override val msgType: Int get() = MsgType.OTA_DATA
    override val isResponse: Boolean get() = true
    var nextOffset: Long? = null

    override fun write(w: TlvWriter) {
        nextOffset?.let { w.u32(0x01, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): OtaDataResp {
            val m = OtaDataResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.nextOffset = r.u32()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class OtaEndReq : ProtoMessage {
    override val msgType: Int get() = MsgType.OTA_END
    override val isResponse: Boolean get() = false

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): OtaEndReq {
            val m = OtaEndReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class OtaEndResp : ProtoMessage {
    override val msgType: Int get() = MsgType.OTA_END
    override val isResponse: Boolean get() = true

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): OtaEndResp {
            val m = OtaEndResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class OtaAbortReq : ProtoMessage {
    override val msgType: Int get() = MsgType.OTA_ABORT
    override val isResponse: Boolean get() = false

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): OtaAbortReq {
            val m = OtaAbortReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class OtaAbortResp : ProtoMessage {
    override val msgType: Int get() = MsgType.OTA_ABORT
    override val isResponse: Boolean get() = true

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): OtaAbortResp {
            val m = OtaAbortResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class OtaStatusReq : ProtoMessage {
    override val msgType: Int get() = MsgType.OTA_STATUS
    override val isResponse: Boolean get() = false

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): OtaStatusReq {
            val m = OtaStatusReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class OtaStatusResp : ProtoMessage {
    override val msgType: Int get() = MsgType.OTA_STATUS
    override val isResponse: Boolean get() = true
    var state: Int? = null
    var received: Long? = null
    var error: Int? = null

    override fun write(w: TlvWriter) {
        state?.let { w.u8(0x01, it) }
        received?.let { w.u32(0x02, it) }
        error?.let { w.u8(0x03, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): OtaStatusResp {
            val m = OtaStatusResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.state = r.u8()
                    2 -> m.received = r.u32()
                    3 -> m.error = r.u8()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class OtaConfirmReq : ProtoMessage {
    override val msgType: Int get() = MsgType.OTA_CONFIRM
    override val isResponse: Boolean get() = false

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): OtaConfirmReq {
            val m = OtaConfirmReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class OtaConfirmResp : ProtoMessage {
    override val msgType: Int get() = MsgType.OTA_CONFIRM
    override val isResponse: Boolean get() = true

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): OtaConfirmResp {
            val m = OtaConfirmResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class RebootReq : ProtoMessage {
    override val msgType: Int get() = MsgType.REBOOT
    override val isResponse: Boolean get() = false

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): RebootReq {
            val m = RebootReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class RebootResp : ProtoMessage {
    override val msgType: Int get() = MsgType.REBOOT
    override val isResponse: Boolean get() = true

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): RebootResp {
            val m = RebootResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class FactoryResetReq : ProtoMessage {
    override val msgType: Int get() = MsgType.FACTORY_RESET
    override val isResponse: Boolean get() = false
    var mode: Int? = null

    override fun write(w: TlvWriter) {
        mode?.let { w.u8(0x01, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): FactoryResetReq {
            val m = FactoryResetReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.mode = r.u8()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class FactoryResetResp : ProtoMessage {
    override val msgType: Int get() = MsgType.FACTORY_RESET
    override val isResponse: Boolean get() = true

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): FactoryResetResp {
            val m = FactoryResetResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class IdentifyReq : ProtoMessage {
    override val msgType: Int get() = MsgType.IDENTIFY
    override val isResponse: Boolean get() = false
    var seconds: Int? = null

    override fun write(w: TlvWriter) {
        seconds?.let { w.u8(0x01, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): IdentifyReq {
            val m = IdentifyReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.seconds = r.u8()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class IdentifyResp : ProtoMessage {
    override val msgType: Int get() = MsgType.IDENTIFY
    override val isResponse: Boolean get() = true

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): IdentifyResp {
            val m = IdentifyResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class LogReq : ProtoMessage {
    override val msgType: Int get() = MsgType.LOG
    override val isResponse: Boolean get() = false
    var level: Int? = null
    var tag: String? = null
    var text: String? = null
    var tsMs: Long? = null

    override fun write(w: TlvWriter) {
        level?.let { w.u8(0x01, it) }
        tag?.let { w.str(0x02, it, 16) }
        text?.let { w.str(0x03, it, 200) }
        tsMs?.let { w.u64(0x04, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): LogReq {
            val m = LogReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.level = r.u8()
                    2 -> m.tag = r.str()
                    3 -> m.text = r.str()
                    4 -> m.tsMs = r.u64()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class PairCodeReq : ProtoMessage {
    override val msgType: Int get() = MsgType.PAIR_CODE
    override val isResponse: Boolean get() = false
    var code: Int? = null

    override fun write(w: TlvWriter) {
        code?.let { w.u16(0x01, it) }
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): PairCodeReq {
            val m = PairCodeReq()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    1 -> m.code = r.u16()
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

class PairCodeResp : ProtoMessage {
    override val msgType: Int get() = MsgType.PAIR_CODE
    override val isResponse: Boolean get() = true

    override fun write(w: TlvWriter) {
    }

    companion object {
        fun read(data: ByteArray, off: Int = 0, end: Int = data.size): PairCodeResp {
            val m = PairCodeResp()
            val r = TlvReader(data, off, end)
            while (r.next()) {
                when (r.tag and 0x7F) {
                    else -> r.unknown()
                }
            }
            return m
        }
    }
}

object Messages {
    fun readRequest(type: Int, data: ByteArray, off: Int, end: Int): ProtoMessage? = when (type) {
        MsgType.HELLO -> HelloReq.read(data, off, end)
        MsgType.PING -> PingReq.read(data, off, end)
        MsgType.DESCRIBE -> DescribeReq.read(data, off, end)
        MsgType.STATE -> StateReq.read(data, off, end)
        MsgType.REPORT -> ReportReq.read(data, off, end)
        MsgType.SET -> SetReq.read(data, off, end)
        MsgType.GET -> GetReq.read(data, off, end)
        MsgType.INVOKE -> InvokeReq.read(data, off, end)
        MsgType.EVENT -> EventReq.read(data, off, end)
        MsgType.CFG_GET -> CfgGetReq.read(data, off, end)
        MsgType.CFG_SET -> CfgSetReq.read(data, off, end)
        MsgType.WIFI_SCAN -> WifiScanReq.read(data, off, end)
        MsgType.NET_STATUS -> NetStatusReq.read(data, off, end)
        MsgType.OTA_BEGIN -> OtaBeginReq.read(data, off, end)
        MsgType.OTA_DATA -> OtaDataReq.read(data, off, end)
        MsgType.OTA_END -> OtaEndReq.read(data, off, end)
        MsgType.OTA_ABORT -> OtaAbortReq.read(data, off, end)
        MsgType.OTA_STATUS -> OtaStatusReq.read(data, off, end)
        MsgType.OTA_CONFIRM -> OtaConfirmReq.read(data, off, end)
        MsgType.REBOOT -> RebootReq.read(data, off, end)
        MsgType.FACTORY_RESET -> FactoryResetReq.read(data, off, end)
        MsgType.IDENTIFY -> IdentifyReq.read(data, off, end)
        MsgType.LOG -> LogReq.read(data, off, end)
        MsgType.PAIR_CODE -> PairCodeReq.read(data, off, end)
        else -> null
    }

    fun readResponse(type: Int, data: ByteArray, off: Int, end: Int): ProtoMessage? = when (type) {
        MsgType.HELLO -> HelloResp.read(data, off, end)
        MsgType.PING -> PingResp.read(data, off, end)
        MsgType.DESCRIBE -> DescribeResp.read(data, off, end)
        MsgType.SET -> SetResp.read(data, off, end)
        MsgType.GET -> GetResp.read(data, off, end)
        MsgType.INVOKE -> InvokeResp.read(data, off, end)
        MsgType.CFG_GET -> CfgGetResp.read(data, off, end)
        MsgType.CFG_SET -> CfgSetResp.read(data, off, end)
        MsgType.WIFI_SCAN -> WifiScanResp.read(data, off, end)
        MsgType.NET_STATUS -> NetStatusResp.read(data, off, end)
        MsgType.OTA_BEGIN -> OtaBeginResp.read(data, off, end)
        MsgType.OTA_DATA -> OtaDataResp.read(data, off, end)
        MsgType.OTA_END -> OtaEndResp.read(data, off, end)
        MsgType.OTA_ABORT -> OtaAbortResp.read(data, off, end)
        MsgType.OTA_STATUS -> OtaStatusResp.read(data, off, end)
        MsgType.OTA_CONFIRM -> OtaConfirmResp.read(data, off, end)
        MsgType.REBOOT -> RebootResp.read(data, off, end)
        MsgType.FACTORY_RESET -> FactoryResetResp.read(data, off, end)
        MsgType.IDENTIFY -> IdentifyResp.read(data, off, end)
        MsgType.PAIR_CODE -> PairCodeResp.read(data, off, end)
        else -> null
    }
}
